### ISSUE TITLE
[3.7.5] Release new version

### ISSUE THREAD

**Issue by nasli** [owncloud/ios#1030]
#Release a new version
## TASKS:
- [x] [GIT] Create branch release_3.7.5 (freeze the code)
- [x] [DIS] Update changelog ios app
- [x] [DEV] Update version number
- [x] [DEV] Update readme number version app
- [x] [DEV] Update third party file
- [X] [QA] Design Test plan @jesmrec
- [x] [QA] Regression Test @jesmrec
- [x] [DIS] Create itunes new version
- [x] [DIS] Upload new ipa to appstore
- [x] [DIS] Upload ipas to repos
- [x] [GIT] Merge branch release into master and stable
- [x] [GIT] Create tag and sign it

PR: https://github.com/owncloud/ios/pull/1058

**Comment by jesmrec** [comment]
Approved

**Comment by jesmrec** [comment]
SAML also passed and approved. Ready to ship.

CC @michaelstingl @javiergonzper
