### ISSUE TITLE
[3.8.0] Release new version

### ISSUE THREAD

**Issue by jesmrec** [owncloud/ios#1076]
#Release a new version

## TASKS:
- [x] [GIT] Create branch release_3.8.0 (freeze the code)
- [x] [DIS] Update changelog ios app
- [x] [DEV] Update version number
- [x] [DEV] Update readme number version app
- [x] [DEV] Get latest translations from master
- [x] [QA] Design Test plan @jesmrec
- [x] [QA] Regression Test  @jesmrec
- [x] [DIS] Create itunes new version
- [x] [DIS] Upload new ipa to appstore
- [x] [DIS] Upload ipas to repos
- [x] [GIT] Create tag and sign it
- [x] [GIT] Merge branch release
- [x] [DIS] Create post in central 

___

BUGS & IMPROVEMENTS:

**Comment by jesmrec** [comment]
Ready to be launched.

**Comment by lefherz** [comment]
Hi, I can't see the updated changelog, neither on the master branch nor on http://owncloud.org/changelog/ios. 

Also I think some of those boxes need to be checked :)

will there be a central post about the release? We could use it to announce the release on social media.

**Comment by jesmrec** [comment]
the `release_3.8.0` branch was not merged yet. The file is inthere: https://github.com/owncloud/ios/blob/release_3.8.0/Changelog.md  within the branch. 

we can write an small post on central about. This release is mainly a bug fixing one, so no much new stuff to offer. I will take care.

**Comment by jesmrec** [comment]
@emil all stuff is already merged, changelog available in `master` branch

**Comment by lefherz** [comment]
wonderful! I can see it on https://owncloud.org/changelog/ios/. Ping me
when you have a central post so we can start the communication :)

**Comment by jesmrec** [comment]
![screen shot 2018-09-11 at 18 36 28](https://user-images.githubusercontent.com/14894746/45374190-aaacd780-b5f1-11e8-9454-3937bd8e0b69.png)

**Comment by jesmrec** [comment]
@lefherz here it is the central post: https://central.owncloud.org/t/owncloud-ios-3-8-0-released/15550

I have no permissions to pin the post to keep it on the top. Who is taking care about that?

**Comment by lefherz** [comment]
I pinned the topic and scheduled a post about it tomorrow at 13:45. I think we can close this :)

**Comment by jesmrec** [comment]
Thanks everyoone for your work!!
