### ISSUE TITLE
Release 3.8.1

### ISSUE THREAD

**Issue by jesmrec** [owncloud/ios#1100]
#Release a new version

## TASKS:

- [ ] [DIS] Update changelog ios app
- [ ] [DEV] Update version number
- [ ] [DEV] Update readme number version app
- [ ] [DEV] Get latest translations from master
- [ ] [QA] Smoke Test  @jesmrec
- [ ] [QA] Upgrade Test  @jesmrec
- [ ] [DIS] Create itunes new version
- [ ] [DIS] Upload new ipa to appstore
- [ ] [DIS] Upload ipas to repos
- [ ] [GIT] Create tag and sign it
- [ ] [GIT] Merge branch release
- [ ] [GIT] Update stable release
- [ ] [DIS] Create post in central

**Comment by jesmrec** [comment]
Year upgraded.

From my side is OK to move forward @javiergonzper

**Comment by jesmrec** [comment]
Cloud icon in the top bar is darker as usual, leading to colour confusion in case of branding:

![screen shot 2019-02-12 at 18 30 31](https://user-images.githubusercontent.com/14894746/52655433-7321be80-2ef4-11e9-9c87-b03a7e12f415.png)

iOS12 and XCode10. We should take a look for the incoming upgrade of XCode

**Comment by jesmrec** [comment]
In iPad, the allignment of the top bar is lost:

In 3.8.0:

![screen shot 2019-02-13 at 09 32 20](https://user-images.githubusercontent.com/14894746/52697892-b0c52c80-2f72-11e9-99c0-3262409c72ba.png)

in 3.8.1:

![screen shot 2019-02-13 at 09 34 13](https://user-images.githubusercontent.com/14894746/52697898-b7ec3a80-2f72-11e9-8d82-c448bdcd98c1.png)

iOS12, iPadAir2

**Comment by jesmrec** [comment]
### (3)

1. Download a file (not a pic), so you can check the download progress. A huge file will help to reproduce
2. Cancel the download by tapping on (x) 

Current: Nothing happens, file keeps downloading
Expected: Download cancelled

iOS12 iPadAir2 

NOTE: Not a regression, but in iPad the progress does not appear (in iPhone, does)

**Comment by jesmrec** [comment]
All stuff fixed, and upgrading to 3.8.1 was correct.

Approved, ready to go to the AppStore.

CC @hosy @michaelstingl
