### ISSUE TITLE
Change StatusBar text Color to black

### ISSUE THREAD

**Issue by supportreq** [owncloud/ios#538]
For iOS 8, 9 and up is it possible to change the statusbar text item color to black?

Please advice.. the customization.h has k_is_text_status_bar_white, but doesnt seem to work with the new ios..

TASKS

- [X] [BUG] Uploader view shows status bar always black https://github.com/owncloud/ios/issues/676 @mRoRo (won't fix)
- [X] [BUG][iPad] Message "Updating file" is not displayed https://github.com/owncloud/ios/issues/677 @mRoRo
- [X] [BUG] Message "Updating file" is not correctly view with some branding options https://github.com/owncloud/ios/issues/678 @mRoRo [FIXED]

PR: https://github.com/owncloud/ios/pull/659

**Comment by javiergonzper** [comment]
If that flag is not working probably we have a bug...
Thanks for report!

**Comment by supportreq** [comment]
@javiergonzper anyone working on this?

**Comment by nasli** [comment]
Hello @supportreq, it is on the top of the backlog and we expect to review it within a short time

**Comment by supportreq** [comment]
@nasli this seems to work on the Login Page :+1: 
For others it is not working 
```
//For one of the next user story
-(UIStatusBarStyle)preferredStatusBarStyle {
    
    if (k_is_text_status_bar_white) {
        return UIStatusBarStyleLightContent;
    } else {
        return UIStatusBarStyleDefault;
    }
}
```

**Comment by ggdiez** [comment]
@supportreq the "k_is_text_status_bar_white" flag it is only for the login view. In the rest of the app the status bar color is always white.

**Comment by supportreq** [comment]
@ggdiez can we not change the colour for other views?
 cause in case we follow apps like Drive, Mail most of them have a whitish navigation bar and not coloured..

**Comment by rperezb** [comment]
@supportreq for the moment this option is not included among the branding options, indeed, this is the first request for it.

We do appreciate pull request, would you like to implement it? We just need you to sign the contributor agreement https://owncloud.org/contribute/agreement/ 

Thanks!

**Comment by jancborchardt** [comment]
The default for the standard blue header should definitely stay white, especially because all the action icons, logos and text are white as well.

If there is a black/white setting for the header text/icons/logo, the status bar color should simply use the same value.

**Comment by supportreq** [comment]
I was able to resolve this but i m not sure how do i share the code.. The following code needs to be updated on almost all pages wherever the return (UIStatusBarStyle)preferredStatusBarStyle code is present to : 

`-(UIStatusBarStyle)preferredStatusBarStyle {

    if (k_is_text_status_bar_white) {
        return UIStatusBarStyleLightContent;
    } else {
        return UIStatusBarStyleDefault;
    }
}`

**Comment by rperezb** [comment]
Thanks for that!
First step we'd need you to sing the contributor agreement (https://owncloud.org/contribute/agreement/) and then send it to @karlitschek 
Once, you have this, you may follow the info on: https://github.com/owncloud/ios/blob/develop/OCC2015_iOS_workshop.pdf about how to contribute

Plus, we'd appreciate a new variable for the status bar on the app, instead of using the same one used on the login screen. The reason is because we may have a light color used as background on the login view so that needed black text, while the top bar could be dark so that we'd rather the opposite, white text.

Thanks!

**Comment by rperezb** [comment]
Work done in https://github.com/owncloud/ios/tree/status_bar_text_color_branding
cc @jesmrec

**Comment by rperezb** [comment]
For reference, a new branding variable has been added https://github.com/owncloud/ios/blob/status_bar_text_color_branding/Owncloud%20iOs%20Client/Branding/Customization.h#L124

**Comment by mRoRo** [comment]
TASKS

- [] [BUG] Uploader view shows status bar always black @mRoRo [WIP]
- [] [BUG][iPad] Message "Updating file" is not displayed
- [] [BUG] Message "Updating file" is not correctly view with some branding options
