### ISSUE TITLE
[Clear cache&Remove account] As an iOS user I want to be able to delete the downloaded data on my device so that I don't run out of space

### ISSUE THREAD

**Issue by nasli** [owncloud/ios#657]
AC:
- Add an button to delete all the downloaded data on an account -> the selected account #301
- This user story includes the change of place of the option to log out. #640
- UI: #640 (comment)

IMPORTANT:
- Favorite offline synced data won't be removed
- Check single account vs multiaccount

TASKS:
- [x] [GIT] Create branch https://github.com/owncloud/ios/tree/clear_cache_button @javiergonzper 
- [X] [DEV] Add direct clear cache button in settings view @javiergonzper 
- [X] [DEV] Create delete all local files downloaded except the favourites @javiergonzper 
- [X] [DEV] Update settings view in order to use old look but remain the refactor per multiaccount, options per account will be set in other menu @nasli
- [X]  [DEV] Add dot button instead of current info icon in account rows in Settings view @nasli
- [X] [DEV] Add new menu view with options "Edit Account", "Clear Cache", "Log out"  @nasli
- [X] [DEV] Add logic edit account in menu option @nasli
- [X] [DEV] Add logic log out in menu option @nasli
- [X] [DEV] Updated view in order to use also disclosure instead of dots button [Won't Fix] @nasli We use the event of tap in the row to select active account, we would need to use DetailDisclosureButton instead of the disclosureIndicator and now looks like
<img width="47" alt="detaildisclosurebutton" src="https://cloud.githubusercontent.com/assets/6570505/15423015/b39bf264-1e7b-11e6-8cfd-d4efdcc432af.png">. For the moment we consider better UX use the three dot button
- [X] [DEV] Check Title to correct fit with longer accounts names  @nasli
- [X] [DEV] Check constraints username account cell @nasli
- [X] [DEV] Add logic clear cache new button menu @nasli 
- [X] [DEV] Update title menu with "@" between username and account url @nasli
- [X] [BUG] Crash after switch between accounts @nasli [cannot reproduce]
- [X] [DEV] Update wording "Edit Credentials" @nasli
- [X] [DEV] Update wording "Remove account" @nasli
- [X] [DEV] Define single account UI. Show account also account section @nasli
- [X] [QA] Create Test plan: https://github.com/owncloud/QA/issues/235 @jesmrec 
- [X] [QA] Validate Test plan @jesmrec
- [X] [GIT] Merge branch "clear_cache_button" @mRoRo 

BUGS:
- [X] Option "Edit Credentials" does not work in iPad https://github.com/owncloud/ios/issues/672 @nasli
- [X] Clearing cache with a spinner https://github.com/owncloud/ios/issues/673 @mRoRo
- [X] Menu chart displaced in iPad https://github.com/owncloud/ios/issues/675 @nasli

PR:https://github.com/owncloud/ios/pull/669

**Comment by nasli** [comment]
@jesmrec ready to review!

**Comment by jesmrec** [comment]
Approved!!

cc @nasli @mRoRo @javiergonzper
