### ISSUE TITLE
[AFN3] Update the network library to Afnetworking3

### ISSUE THREAD

**Issue by rperezb** [owncloud/ios#662]
This implies work in the app as well as work in the library

WIP
- https://github.com/owncloud/ios/tree/adapt_the_app_to_owncloud_lib_v2
- https://github.com/owncloud/ios-library/tree/adapt_the_app_to_owncloud_lib_v2_library

TASKS:
- [x] [GIT] Create branch "adapt_the_app_to_owncloud_lib_v2" @javiergonzper 
- [ ] [GIT] Merge branch "adapt_the_app_to_owncloud_lib_v2"
- [X] [QA] Create Test plan  @jesmrec https://github.com/owncloud/QA/issues/245
- [X] [QA] Validate Test plan@jesmrec
- [X] [DEV] Fix the problems connecting with SAML to an ownCloud server @javiergonzper 
- [X] [DEV] When pull down to refresh do not detect the SAML expiration @javiergonzper 
- [X] [DEV] Refactor Login SSO classes to use NSURLSession instead of NSURLConnection @mRoRo (won't fix)
- [X] [DEV] Refactor OfficeFileView using NSURLSession instead of NSURLConnection @javiergonzper 
- [X] [DEV] Change configuration in CheckAccessToServer @MorrisJobke 

PR:https://github.com/owncloud/ios/pull/674

___

BUGS / IMPROVEMENTS

- [X] App freezes when displays the file view https://github.com/owncloud/ios/issues/662#issuecomment-224878988 @nasli
- [X] Black screen when touch id/passcode are enabled https://github.com/owncloud/ios/issues/662#issuecomment-226110614 @nasli
- [X] Upload not resumed when the session in saml expires https://github.com/owncloud/ios/issues/662#issuecomment-226167010 @nasli [not fixed, no regression, moved as other use case into https://github.com/owncloud/ios/issues/695#issuecomment-226242571]
- [X] Background downloads in SAML https://github.com/owncloud/ios/issues/662#issuecomment-227363685 -> moved to 
- [X] Actions after session expiration https://github.com/owncloud/ios/issues/662#issuecomment-227426807 @mRoRo [FIXED]
- [X] Uploads after session expiration https://github.com/owncloud/ios/issues/662#issuecomment-228733108 @mRoRo

**Comment by jesmrec** [comment]
@nasli 

Please, check this behaviour in the feature branch:

1.- In settings, create accounts (one is enough). (Upgrading from another version/branch fits as well to reproduce it)
2.- Kill the app
3.- Open the app

The app freezes during some seconds, and after that, the list view is displayed.

Tested with iPhone6 v9.3.2 (freezes on a black background) and iPad Air v8.4 (freezes on a withe background).

**Comment by nasli** [comment]
@jesmrec I can reproduce it also without upgrading. Just kill the app and open it.

**Comment by jesmrec** [comment]
The point is when accounts are already stored in keychain -> the problem happens

**Comment by nasli** [comment]
Fixed @jesmrec, there was a problem with some action that update the interface in a background queue due new sessions

**Comment by jesmrec** [comment]
i will check it asap :)

**Comment by jesmrec** [comment]
@nasli The problem with the splash screen is already solved 👍 

But, there are exceptions. Basically, when the passcode/touch id are enabled and the app is opened, the screen turns black and freezed during some seconds, and after that is shown the files view

Please check it :)

**Comment by nasli** [comment]
Ok @jesmrec, fixed passcode view :)

**Comment by jesmrec** [comment]
### Bug

In a shibboleth server, try tu upload a huge file (a video, for example). When the session expires and the file is not completely uploaded, input the credentials.  

The upload is not resumed (related to #695 ¿?)

**Comment by nasli** [comment]
Yes @jesmrec, looks like the same that #695 and also happens within 3.4.9, it is not a regression, let's move it as other user case in #695

**Comment by jesmrec** [comment]
Downloads en SAML servers in background are not working well. 

Follow the next steps:

1.- In a SAML server, set a expiration time of 8 mins
2.- Connect to the server and download a huge file
3.- Lock the device in order to enable the background after 3 mins
4.- After 5 or 6 minutes (before the session expires) open the app

Actual behaviour: the download was stopped

Expected behaviour: The download finished or keeps on working

Tested with iPadAir v8.4 and iPhone 9.1

**Comment by jesmrec** [comment]
Respect the previous behaviour, is also happening in master, so can be handled in another issue.

**Comment by jesmrec** [comment]
### Bug

Steps:

1. Wait until a SAML session expires (do not perform any action)
2. Swipe to delete/rename/move a folder

Actual Behaviour

Folder is deleted/renamed/moved in device but not in server. Inputing the credentials again and pulling down, the updated folders return to the previous status

Expected behaviour

If the session has expired, any action performed on a folder forces to input again the credentials.

Tested with iPadAir v8.4 and iPhone v9.1

**Comment by nasli** [comment]
Great @mRoRo!! @jesmrec, validation can continue  :smiley:

**Comment by mRoRo** [comment]
### Bug

Steps:

1. Wait until a SAML session expires (do not perform any action) in files view
2. Press 3 dots button and select Upload Photo/Video
3. Select a photo and try to upload it

Actual Behaviour

Nothing seems to happen in real devices

Expected behaviour

If the session has expired, a alert is shown and the app forces to input again the credentials.

Tested with iPhone 6 v8.1.3

**Comment by jesmrec** [comment]
Bugs checked and fixed.

Approved.

**Comment by nasli** [comment]
I'm going to close #674 and generate new one against master branch
