### ISSUE TITLE
[EDIT TEXTS] I want to be able to edit .txt files within the iOS app

### ISSUE THREAD

**Issue by rperezb** [owncloud/ios#664]
#- Following the work done in https://github.com/owncloud/ios/issues/195
- I want to be able to edit a text file.
- When previewing a text file within the iOS app, an EDIT button (top right corner) will open a new view: EDIT VIEW.
- EDIT VIEW will have two buttons: CANCEL (changes are not saved) and DONE (changes are saved).
- When leaving the EDIT VIEW, if there were any changes they will be automatically uploaded.
- In case of any errors (network, conflict..) they will be handled as any upload error, meaning this from the uploads view.
- The name of the file will be shown in the TITLE of the EDIT VIEW.
- In the EDIT VIEW the TAB BAR is not shown.
- Related issue: #486

TASKS:

- [X] [GIT] Create branch "edit_text_files" @nasli
- [ ] [GIT] Merge branch "edit_text_files"
- [X] [DEV] Add button Edit on preview view @nasli
- [X] [DEV] Reuse create view with new UI (hide title field) @nasli
- [X] [DEV] Only add edit button in text files. @nasli
- [X] [DEV] Use full view with the body text field @nasli
- [X] [DEV] Check done upload changes  @nasli
- [X] [DEV] Go to root file folder view after edited the file @nasli
- [X] [DEV] Update file version states @nasli
- [X] [DEV] Add edit button feature in ipad view @nasli
- [X] [DEV] Not upload file if no changes made @nasli
- [X] [NTH] Refresh ipad view after uploaded @nasli
- [X] [DEV] Move progress bar to the left in editing files @nasli
- [X] [QA] Create test plan @jesmrec
- [X] [QA] Validate test plan @jesmrec 

BUGS & IMPROVEMENTS:

- [X] Encoded blanks in filename https://github.com/owncloud/ios/issues/664#issuecomment-229586507 @nasli  [FIXED]
- [X] rtf files https://github.com/owncloud/ios/issues/664#issuecomment-229588121 @nasli [WON'T FIX] Is the expected behaviour https://github.com/owncloud/ios/issues/664#issuecomment-229589125
- [X] long filenames https://github.com/owncloud/ios/issues/664#issuecomment-229590658 @nasli [FIXED]
- [X] new text files in feature branch https://github.com/owncloud/ios/issues/664#issuecomment-229598992  @nasli [FIXED]
- [X] edit non-downloaded txt files https://github.com/owncloud/ios/issues/664#issuecomment-229880904 @nasli [FIXED]
- [X] edit updated text https://github.com/owncloud/ios/issues/664#issuecomment-230217985 @nasli[FIXED]

PR: #709

**Comment by nasli** [comment]
Ready to test @jesmrec in PR #709 :)

**Comment by jesmrec** [comment]
### Steps:

1. Set a txt file that has a blank in its name. For example: `hello world.txt`
2. Download the file and open the edit view

### Actual behaviour

In the top bar the file name is shown as `hello%20world.txt`

### Expected behaviour

In the top bar the file name is shown as `hello world.txt`, without encoding the blank.

cc @nasli

**Comment by jesmrec** [comment]
### Bug

### Steps:

1. Download to the device a .rtf file
2. Open the edit view

### Actual behaviour

In the edit view is show all the content included headers, metainfo etc... 

### Expected behaviour

It is shown the same as the preview

cc @nasli

**Comment by nasli** [comment]
@jesmrec yes,https://github.com/owncloud/ios/issues/664#issuecomment-229588121 is the expected behaviour, in the preview it is show the text interpreted (since give more value) but in the edit view as plain text as in web interface

**Comment by jesmrec** [comment]
Setting a txt file with a long filename

The preview shows the filename as

`filenameverylong...niceday.txt`

The edit view shows the filename as

`filenameverylongiwishyoua...`

Both views should display the filename with the same format.

**Comment by jesmrec** [comment]
### Bug

Option "New text file" in three-dot-menu does not work in the feature branch. 

In uploads view is received always a "File error" 

In `master` branch works properly

**Comment by jesmrec** [comment]
@nasli 

check this: https://github.com/owncloud/ios/issues/664#issuecomment-229590658

in iPad v8.4

**Comment by jesmrec** [comment]
### Feature

Steps:

1. Switch the device connection off
2. Tap on a non-downloaded txt file
3. A no-connection file is displayed, accept it

Actual behaviour

The file can not be downloaded, but can be edited as a new file. If the connection would enable, the previous content of the txt file will be overrided

Expected behaviour

Difficult to say...

**Comment by nasli** [comment]
Related https://github.com/owncloud/ios/issues/664#issuecomment-229880904, I would remove the edit button if the file is not downloaded

**Comment by nasli** [comment]
@jesmrec fixed https://github.com/owncloud/ios/issues/664#issuecomment-229880904, not allowed to open edit view if the file is not downloaded

**Comment by jesmrec** [comment]
The same feature as https://github.com/owncloud/ios/issues/664#issuecomment-229880904 happens when the file is updated to a new version from server side or other client:

1. In mobile, download the txt file
2. In server, modify the txt file
3. In mobile, the new version is detected
4. Tap on the file to update and then in "Edit"
5. Edit the txt

The updated version in mobile is updated before the changes are downloaded.

**Comment by jesmrec** [comment]
Approved :)

**Comment by nasli** [comment]
Great!! Thanks @jesmrec!  

@mRoRo , @Jon-Schneider, @ggdiez would you like to review it ?
