### ISSUE TITLE
[Available offline] Favorite feature will be renamed to available offline to avoid misunderstanding between server and mobile features

### ISSUE THREAD

**Issue by rperezb** [owncloud/ios#665]
AC:
- Rename favorite option to "Available offline"
- Rename unfavorite option to "Not available offline"
- Update the icons, the idea is use ones pretty similar to the desktop client, looking to parity within the platform

- These icons will be placed on the top right, over the file/folder icon
+ When the file/folder is being synced we https://github.com/owncloud/client/blob/master/theme/colored/state-sync-256.png
+ When the file/folder is synced https://github.com/owncloud/client/blob/master/theme/colored/state-ok-256.png
+ When there is any conflict https://github.com/owncloud/client/blob/master/theme/colored/state-error-256.png

- When the file has been set as "Available offline" it will be added on the botton right, over the file/folder icon an arrow, icon pending. This will be the icon used within the preview view to set a file as "available offline"

Related to: https://github.com/owncloud/android/issues/1218#issuecomment-219725127

TASKS
- [X] [GIT] Create branch "favorite_rename_as_available_offline" @mRoRo
- [ ] [GIT] Merge branch "favorite_rename_as_available_offline"
- [X] [DEV] Get the correct image sizes from svg icon files @mRoRo
- [X] [DEV] Get a new icon to show that a new version is available in the server but not downloaded in the iOS device. It will be the same as synced but in grey color @mRoRo
- [X] [DEV] Change available offline icon in tab bar @mRoRo
- [X] [DEV] Change status icons in file list views @mRoRo
- [X] [DEV] Change available offline icon in file list views @mRoRo
- [X] [DEV] Rename favorites as available offline strings @mRoRo
- [X] [DEV] Modify error messages "parent_folder_is_available_offline" to distinguish between children folders or files @mRoRo https://github.com/owncloud/ios/issues/665#issuecomment-223019217
- [X] [DEV] Check if any branded option needs to be modified @nasli [Updated downloaded icon that is brandeable]
- [X] [QA] Create test plan @jesmrec
- [X] [QA] Validate test plan [WIP] @jesmrec

PR:  #690

___

BUGS & IMPROVEMENTS

- [X] Yellow arrow does not disappear https://github.com/owncloud/ios/issues/665#issuecomment-225862679 @nasli [FIXED]
- [X] Previous one, but only folders https://github.com/owncloud/ios/issues/665#issuecomment-226427169 [FIXED]
- [X] Available offline icon's size https://github.com/owncloud/ios/issues/665#issuecomment-226460192 @nasli [WON'T FIX will keep same size for both icons]

**Comment by rperezb** [comment]
@michaelstingl this is likely to be interesting for you ㊙️

**Comment by mRoRo** [comment]
The error message colud be: "A folder that contains this **file** is already available offline" for childern files and "A folder that contains this **folder** is already available offline" for folders.

Till the momment the same message was shown for files and folders

**Comment by jesmrec** [comment]
## BUG

### Steps to reproduce

1. Set a file or folder as "Available Offline"
2. Unset the file or folder as "Available Offline"

### Actual behaviour

The yellow arrow does not disappear

### Expected behaviour

The yellow arrow disappears, so that the file is no more available offline

Tested with: iPhone6 v9.3.2. iPadAir v8.4

Server v9.1beta

**Comment by nasli** [comment]
@jesmrec fixed!

**Comment by jesmrec** [comment]
@nasli, works fine with files. But folders are not really working. They remain the arrow although they are not available offline

**Comment by nasli** [comment]
Ok, I edit a added new fix for folder too. Try now ;)

**Comment by jesmrec** [comment]
A posible improvement (open discussion). Do you mean that "available offline" icon is a bit small? 

This is the Android one:

![screen shot 2016-06-16 at 13 28 10](https://cloud.githubusercontent.com/assets/14894746/16115336/aabe0c08-33c6-11e6-8737-cc0b54325f4e.png)

and the iOS one:

![screen shot 2016-06-16 at 13 30 00](https://cloud.githubusercontent.com/assets/14894746/16115347/b3f19bbe-33c6-11e6-8807-e26ee87b2d6c.png)

The green tick highlights much more as the yellow arrow in the iOS app.

**Comment by nasli** [comment]
Yes, I liked as it is, both icons have the same size, take into account that the iOS app has smaller rows.

@owncloud/designers, @Jon-Schneider any input here?

**Comment by Jon-Schneider** [comment]
I like the sizing of the icons as-is. However, I think the yellow is visually unappealing - why not just use green (or another high contrast color) for both? It would be easier to see.

**Comment by jesmrec** [comment]
Or a darker ton of yellow

**Comment by jesmrec** [comment]
If you all agree, we can postpone this discussion for another issue or PR.

The current one is approved :)

@nasli
