### ISSUE TITLE
Client does not recognize maintenance mode

### ISSUE THREAD

**Issue by dercorn** [owncloud/ios#714]
### Steps to reproduce
1. Switch ownCloud server into maintenance mode
### Expected behaviour

The iOS client should inform the user that the server currently in maintenance mode or unreachable.
### Actual behaviour

The client shows no message and displays folders as empty
### Affected software versions

All

 
### Tell us what could be improved:

Have the client display a notification when the server is unavailable (HTTP 503)

____

BUGS & IMPROVEMENTS

- [x] Different behaviour in av. offline files and folders https://github.com/owncloud/ios/issues/714#issuecomment-268982714
- [X] Different behaviour in uploads https://github.com/owncloud/ios/issues/714#issuecomment-268987544
- [X] Shibboleth server does not notify the maintenance mode https://github.com/owncloud/ios/issues/714#issuecomment-268992298 [FIXED]

**Comment by nasli** [comment]
Same for the Android Client I guess, cc @davivel 

This is an enhancement for the clients.

**Comment by davivel** [comment]
Related: https://github.com/owncloud/android/issues/1722

**Comment by cdamken** [comment]
[00005749](https://na25.salesforce.com/5003100000cobm7)

**Comment by cdamken** [comment]
@davivel @nasli Is something we can do previous to "backlog"

**Comment by davivel** [comment]
@cdamken , I don't understand what you mean with "previous to backlog"?

Would you recommend this is dealt with higher priority?

**Comment by dercorn** [comment]
@davivel , after talking to @felixboehm , we agreed that this is clearly a bug and not an enhancement. Although this should cause no serious trouble, it would be extremely nice to see this resolved in the next release.

**Comment by davivel** [comment]
At this point, we should clarify "next release".

In the case of iOS, release 3.5.0 is taking an extraordinary time to be ready, and we can't delay it anymore.

Besides, the release after that needs to be really focused in granting correct operation for iOS 10. We are not sure yet of how many problems will appear, if it's not too much maybe we can sneak this in. Maybe. The fact that it's labelled as a bug or an enhancement makes no difference about the complexity to have it solved.

**Comment by dercorn** [comment]
@davivel can you give an estimate on the complexity?

**Comment by davivel** [comment]
Complexity comes from the scope I'm considering is "whenever the iOS app accesses to the server, if this in maintenance mode, alert the user about this state". That leads me to two worries:
 - We have to cover the error in, potentially, all the views of the app.
 - We'll have to prevent to show repeated error messages if the user browses through the app.

If we could narrow down the scope, for instance, report only when the app is opened and/or when the user switches the account, the complexity would be lesser.

Summarizing: UX in the client is not defined, and I'm assuming a worst-case scenario.

**Comment by guruz** [comment]
... a third point to consider is if there is multi account

**Comment by dercorn** [comment]
@guruz @davivel indeed! How does the client connect to the server? Do you read the status.php?

**Comment by davivel** [comment]
Yes, status.php is read during the creation of the account, and also every time the root folder of an account is refreshed.

**Comment by dercorn** [comment]
Couldn't you use that for updating the status in the client? (Just in case you're not already doing exactly that)

**Comment by guruz** [comment]
(note that 503 might come at any time at any request, without having checked status.php in the last few requests. So the more clear indication for maintenance mode is 503 on any request)

**Comment by davigonz** [comment]
This bug could be fixed implementing a http response interceptor, evaluating the code and showing a message about the maintenance mode when the code is 503. 

We don't need to take into account all the views or accounts, the interceptor catches the response wherever the user is browsing. 

I've just started working on it in Android.

**Comment by jesmrec** [comment]
### Bug

 With maintenance mode enabled in server:

 - If you set a folder as av. offline: alert message is shown 
 - If you set a file as av. offline: alert message is not shown

Both are correctly set as av. offline locally, but the way the user is notified should be the same. For this case, also awaring the user when the file is set as av. offline.

Device: iPhone 6Plus v10.1.1
Server 9.1.3

CC @ggdiez

**Comment by jesmrec** [comment]
The same happens with uploads, we have different behaviours:

- Manual uploads: message is shown but files are not queued
- Instant uploads: files are queued *
- Share from external app: message is not shown and files are queued
- New txt file: message is not shown and files are queued

* Instant uploads is kind of different although is a upload as well. Users do not know whether the server is in maintenance mode or not, so their pics an videos have to be queued in order not to lose them.

Device: iPhone 6Plus v10.1.1
Server 9.1.3

CC @ggdiez

**Comment by jesmrec** [comment]
In a shibboleth server with maintenance mode enabled:

1. Set the server URL -> accepted (should it?)
2. Webview is shown and credentials can be input

The following error is shown:

`The server does not return a correct user ID`

Could be prevented the login action in this case? 

CC @ggdiez

**Comment by ggdiez** [comment]
@jesmrec when the user create a new txt file I think that it's better that the upload will be queued, the user has done the effort to write a text, show a message with the maintenance mode and discard the text file I think that is worse.

**Comment by jesmrec** [comment]
@ggdiez i agree in that behaviour for txt files.

**Comment by ggdiez** [comment]
@jesmrec Added support to maintenance mode in SAML login. Ready to test.

**Comment by jesmrec** [comment]
Approved

**Comment by jesmrec** [comment]
solved an merged. closing...
