### ISSUE TITLE
[3.5.1] Release a new version

### ISSUE THREAD

**Issue by nasli** [owncloud/ios#755]
Release a new version, priority iOS10
## TASKS:
- [X] [GIT] Create branch release_3.5.1 (freeze the code) #784
- [X] [GIT] Create branch release_2.0.1 library (freeze the code) https://github.com/owncloud/ios-library/pull/140
- [X] [DIS] Update changelog ios app
- [X] [DEV] Update version number 3.5.1
- [X] [DEV] Update readme number version app and library
- [x] [QA] Design Test plan
- [X] [QA] Regression Test plan @jesmrec  -> Smoke test https://github.com/owncloud/QA/issues/305 
- [X] [DIS] Release to appstore
- [X] [GIT] Merge branch release_3.5.1
- [X] [GIT] Create tag and sign it
- [X] [QA][DEV] iOS10 https://github.com/owncloud/ios/issues/760 @nasli @jesmrec 
- [X] [DIS] Update screenshots readme file
- [X] [DIS] Update Owncloud address, and other data in Apple Store
- [X] [DEV] Update jenkins to xcode8 
- [X] [DEV] Improve travis output test file 

BRANDING CHANGES

REGRESSION BUGS FOUND:
- [X] Alert view $appname, https://github.com/owncloud/ios/issues/755#issuecomment-243495292 [FIXED] https://github.com/owncloud/ios/pull/777
- [X] Crash when cancel downloading folder  https://github.com/owncloud/ios/issues/760#issuecomment-246964530 [FIXED]
- [X] Spinner looping forever in iPad when file is deleted https://github.com/owncloud/ios/issues/755#issuecomment-249784426 [CAN NOT REPRODUCE]

NOT REGRESSION
- [X] Background instant upload disabled https://github.com/owncloud/ios/issues/755#issuecomment-247582434 moves to [3.5.2](https://github.com/owncloud/ios/issues/779)
- [X] Conflicts in instant uploads https://github.com/owncloud/ios/issues/755#issuecomment-247583486 moves to [3.5.2](https://github.com/owncloud/ios/issues/779)
- [X] App icon in files/preview (design) https://github.com/owncloud/ios/issues/755#issuecomment-247972326 moves to [3.5.2](https://github.com/owncloud/ios/issues/779)
- [X] SAML sessions do not resume download of av. offline folders https://github.com/owncloud/ios/issues/755#issuecomment-249915531  moves to [3.5.2](https://github.com/owncloud/ios/issues/779)

**Comment by nasli** [comment]
$appname not replaced in alert view in share in view

**Comment by jesmrec** [comment]
(not regression)

Steps:

1. Enable instant uploads with background
2. Add a new account (or more...)
3. Switch to the new account

Actual Behaviour

Background instant upload is disabled

Expected behaviour

Background instant upload is enabled

Tested with iOS10, 9, 8

**Comment by jesmrec** [comment]
(not regression)

Steps

1. Enable instant uploads
2. Take some photos
3. Close the app and open it again

Actual Behaviour

The last photo/s taken are queued again, causing conflicts if the current account is the same than the current one when the photos were taken (they are already existing). If the current account is a different one, are uploaded to this account.

Expected behaviour

Photos are only once uploaded: to the current account in the moment of the upload.

Tested with iOS 9, 10.

**Comment by jesmrec** [comment]
Files view with an iPad Air

![screen shot 2016-09-19 at 13 46 43](https://cloud.githubusercontent.com/assets/14894746/18630959/a6280434-7e6f-11e6-8d3c-f85df20f918b.png)

The image does not fit with the frame width.

**Comment by nasli** [comment]
@jesmrec  Is this a regression https://github.com/owncloud/ios/issues/755#issuecomment-247972326?

**Comment by jesmrec** [comment]
@nasli it is not regression, also happens in 3.5.0. Changing in first message to "no regression"

**Comment by nasli** [comment]
Ok, let's move it to next release

**Comment by jesmrec** [comment]
Current stable version has no changes from the last version (3.5.0). So, instead of performing a whole regression test, a smoke test and a bug fixing review will be performed. In order to take advantage, the new server version 9.1.1 and some of the maintenance versions will also used to perform the testing.

The smoke test can be tracked: https://github.com/owncloud/QA/issues/305  (linked in first message)

**Comment by jesmrec** [comment]
### Bug (medium severity)

### Steps

1. In a iPad, download a file. Is displayed on the screen right side
2. Delete the file, no matter if locally or from server

### Actual behaviour

A spinner on black background is displayed on the right side

### Expected behaviour

The previous one, showing the ownCloud icon.

Tested with iPadAir v10

cc @nasli

**Comment by jesmrec** [comment]
On the other hand, the crash with the cancelled uploads is fixed.

**Comment by Jon-Schneider** [comment]
@jesmrec I fixed the setting of the Background Instant Upload preference on new accounts.

**Comment by jesmrec** [comment]
@Jon-Schneider is the fix in https://github.com/owncloud/ios/pull/782/commits?

**Comment by Jon-Schneider** [comment]
@jesmrec Yes.

**Comment by jesmrec** [comment]
### Bug

Steps:

1. In SAML, set a folder as av. offline in a session close to expire
2. When it expires, enter again the credentials

Actual behaviour

The download of files in av. offline folder is not resumed

Expected behaviour

The download of files in av. offline folder is resumed

Tested with iPhone v9 and v10, and iPad v10

**Comment by jesmrec** [comment]
related to https://github.com/owncloud/ios/issues/755#issuecomment-249915531. The bug is reproduceable also in 3.5.0, but not all performed test showed the problem. In any case, by reopening the app the downloads are resumed, as a workaround. So, the bug will not be fixed in the current release and will be dealed in 3.5.2

**Comment by jesmrec** [comment]
Approved. Some no-regression bugs delayed to next release:

https://github.com/owncloud/ios/issues/779

**Comment by nasli** [comment]
Updating Xcode8 and OS X in jenkins machine

**Comment by rperezb** [comment]
@nasli time to close this one???
💃

**Comment by nasli** [comment]
All jenkins environment ready to support new Xcode8
