### ISSUE TITLE
iOS10

### ISSUE THREAD

**Issue by nasli** [owncloud/ios#760]
#EDITED @rperezb

The goal of this issue is to compile the app with the latest version of xCode and detect and fix possible errors related to this update

- [X] Compile with xcode 8 @nasli
- [X] Fix travis [WIP]
- [x] Once final iOS10 released try to remove xcodebuild script in travis in order to use xctool [still fails with xctool]
- [X] Run a smoke test plan to detect possible errors @jesmrec -> https://github.com/owncloud/ios/issues/760#issuecomment-243479332
- [X] Testing iOS10 GM @jesmrec

branch: https://github.com/owncloud/ios/tree/ready_to_ios10
PR: https://github.com/owncloud/ios/pull/775

BUGS & IMPROVEMENTS

- [X] Uploads inside the app crash if permission allow access to camera is not enabled [FIXED]
- [X] Cancel Download folder/Av Offline folder crashes https://github.com/owncloud/ios/issues/760#issuecomment-246964530 [DELAYED TO FINAL RELEASE]
- [X] Upper bar colours https://github.com/owncloud/ios/issues/760#issuecomment-247014434, more details https://github.com/owncloud/ios/issues/760#issuecomment-248546278 Let's keep improving for next release
- [X] After granted photo access permission only appears one album https://github.com/owncloud/ios/issues/760#issuecomment-247971195 [FIXED in https://github.com/owncloud/ios/pull/778]

**Comment by jesmrec** [comment]
Smoke test passed.

Only one issue detected but the steps are not clear because it happened only sometimes: 

`Your device does not have the account configured. Go to settings`

when an attached account is selected. I will try to reproduce it again before the release.

**Comment by nasli** [comment]
New test cases on going with the new iOS 10 GM

**Comment by jesmrec** [comment]
### Bug

### Steps

1. Download a folder / Set a folder as available offline
2. Cancel the download

### Actual behaviour

App crashes

### Expected behaviour

Downloaded/Av Off folder

tested with iPad iOS10

**Comment by guruz** [comment]
@nasli I see in some places
```
        if (IS_IOS8 || IS_IOS9)  {
            [self.plusActionSheet showInView:app.splitViewController.view];
        } else {
            [self.plusActionSheet showInView:app.detailViewController.view];
        }
```
Does this need to be adjusted?

**Comment by jesmrec** [comment]
Taking care of the colors in upper bar. These are darker than in previous versions.

**Comment by nasli** [comment]
@guruz,
> Does this need to be adjusted?

YES, we should improve all this IS_IOS versions in order to clean code because they are since iOS6, but no hurry, it will work for iOS10 too
```
#define IS_IOS9 ([[[UIDevice currentDevice] systemVersion] floatValue] >= 9)
```

**Comment by nasli** [comment]
### Bug
After granted photo access permission only appears one album
### Steps

1. Install app
2. Select to upload photo/video in menu option
3. Granted photo access permission

### Actual behaviour
Only appears all_photos album

### Expected behaviour
All albums in the device are shown

tested with iPad iOS10

**Comment by rperezb** [comment]
@hodyroff @felixboehm @michaelstingl FYI new version of the iOS app on going

**Comment by nasli** [comment]
Related to https://github.com/owncloud/ios/issues/760#issuecomment-247014434
Only happens in the top bar with the navigations views, not for new views such create text file.
It happens navigating in:
-File list view
-Photo picker view
-Document provider file list view
-Select folder in: move option, share to owncloud
-From setting view select Add new account
-From setting view Help, Recommend to a Friend.. and rest of options


In share view select Add user

**Comment by jesmrec** [comment]
Related to https://github.com/owncloud/ios/issues/760#issuecomment-248546278

Browsing back in the folders structure, the icons in upper right/left have the dark color.

@nasli

**Comment by jesmrec** [comment]
Approved. Pending issues to be delayed until next release or final test of 3.5.1.

**Comment by nasli** [comment]
Closes via https://github.com/owncloud/ios/pull/775
