### ISSUE TITLE
[3.5.2] Release a new version 

### ISSUE THREAD

**Issue by nasli** [owncloud/ios#779]
Release a new version
# TASKS:
- [X] [GIT] Create branch release_3.5.2 (freeze the code)
- [X] [GIT] Create library branch release_ios_app_3.5.2 (freeze the code)
- [x] [DIS] Update changelog ios app with note latest supported version
- [x] [DEV] Update version number 3.5.2
- [X] [DEV] Update readme number version app and library
- [X] [QA] Design Test plan @jesmrec
- [X] [QA] Regression Test plan @jesmrec
- [x] [DIS] Release to appstore
- [x] [GIT] Merge branch release_3.5.2
- [x] [GIT] Merge library branch release_ios_app_3.5.2 
- [x] [GIT] Create tag and sign it
- [X] [DEV] updated with master and transifex updated for wording

BUGS
- [X] Background instant upload disabled https://github.com/owncloud/ios/issues/755#issuecomment-247582434 [FIXED] https://github.com/owncloud/ios/pull/782
- [X] Conflicts in instant uploads https://github.com/owncloud/ios/issues/803 [FIXED]  https://github.com/owncloud/ios/pull/816
- [X] App icon in files/preview  https://github.com/owncloud/ios/issues/755#issuecomment-247972326  -> [DELAYED] -> https://github.com/owncloud/ios/issues/817.
- [X] Upper bar colours #760 (comment), more details #760 (comment) , https://github.com/owncloud/ios/issues/760#issuecomment-248682039 -> [DELAYED] -> https://github.com/owncloud/ios/issues/817.
- [x] SAML: Resume download of av. offline folders when session expires https://github.com/owncloud/ios/issues/755#issuecomment-249915531 -> [DELAYED] -> https://github.com/owncloud/ios/issues/819
- [X] Username in edit account https://github.com/owncloud/ios/issues/806 [FIXED] 
- [X] Redirection to a server which is hosted in subfolder https://github.com/owncloud/ios/issues/779#issuecomment-264414570 -> [FIXED]
- [x] After adding a redirected server, other servers fail  -> [FIXED] https://github.com/owncloud/ios/issues/779#issuecomment-265392251 
- [x] After deleting and adding the same account and going to Files, the app crashes https://github.com/owncloud/ios/issues/779#issuecomment-266959097 -> [FIXED]

IMPROVEMENTS
- [x] WORDING: "Edit Password" instead of "Edit Credentials" in accounts menu https://github.com/owncloud/ios/issues/779#issuecomment-252586516  -> [READY TO TEST]

PR: https://github.com/owncloud/ios/pull/820
PR library: https://github.com/owncloud/ios-library/pull/142

**Comment by ggdiez** [comment]
awesome

**Comment by jesmrec** [comment]
[WORDING]

What do you think about changing "Edit Credentials" to "Edit Password" in account menu? Credentials mean both username and password and the only editable is the password.

**Comment by jesmrec** [comment]
###Bug

Steps:

Set as URL a redirected server. The target server is hosted in a subfolder (for example http://mydomain.org/owncloud

Actual behaviour

Can not authenticate against this server

Expected behaviour

Server connection established

iPhone6Plus v10.1.1
iPhone6 v9.3.5

**Comment by jesmrec** [comment]
### Bug

Steps

1. Add a redirected server 
2. Add two more accounts (normal servers)
3. Open the file list of these two accounts

Current behaviour

The two accounts attached after the redirected server fail with a credential error in the files view.

Expected behaviour

All accounts work properly

Tested with iPad v9, iPhone 6Plus v10.1.1, iPhone6 v9.3.5
Server 9.1.3, 9.1.2

**Comment by borjahawk** [comment]
Wording change from "Edit Credentials" to "Edit Password" validated.

**Comment by borjahawk** [comment]
### Bug

Preconditions:
Have at least 2 accounts created in an app.

Steps:

1. Open the app
2. Go to Settings view
3. Remove the last account
4. Add the same account
5. Go to Files view 

### Current behaviour

The app crashes.

### Expected behaviour

The app should not crash and show the files.

iPhone6s v9.3
iPhone6 v8.2

**Comment by nasli** [comment]
Good catch @borjahawk! should be fixed now. Updated changes in the branch.

**Comment by kuking** [comment]
Any news on https://github.com/owncloud/ios/issues/770 ? it renders the whole application useless. You will get a lot of "1 star".
