### ISSUE TITLE
As an iOS user I want to be able to stream mp4 files

### ISSUE THREAD

**Issue by nasli** [owncloud/ios#787]
pending the be confirmed

AC:
- I want to stream mp4 files once I tap over a file in file list view instead of downlading it
- If I want to download the file, new "download" option will be added into swipe menu option
- If new version is available it should works as always. Update the current file while play it.
- If the file is being downloaded you can not stream it, and if the user taps over the file a progress bar will be shown
- If the file is in streaming mode, the user won't be able to set up as available offline fron the preview view. Available offline will be only possible from the file list menu
- In the moment the user leaves the preview view the streaming will be stopped

Same for Android 

@davivel , @jesmrec, @rperezb  @felixboehm 

- [x] [GIT] Create branch stream_video_files
- [x] [DEV] Use AVPlayer instead MPMoviePlayer because it is deprecated
- [x] [DEV] Play downloaded files using AVPlayer
- [x] [DEV] Adapt the size of the player to portrait and landscape
- [x] [DEV] Create a similar UX on the AVPlayer to play/pause and full screen
- [x] [DEV] Remove the old MediPlayer class [in progreess]
- [x] [DEV] Play music in background
- [x] [DEV] Control the play/pause buttons to play music
- [x] [DEV] Stream the video files instead download them when the user select one
- [x] [DEV] Control the streaming in order to do ir only on HTTP and HTTPS with valid certificates
- [x] [DEV] Make streaming also with SAML
- [x] [DEV] Adapt the streaming for iPad
- [x] [DEV] Add a download option on the more menu (if the user select download go to preview with a force download)
- [x] [DEV] Add a cancel download option on the more menu if the file is downloading
- [x] [DEV] Not streaming the video if the files is downloading (show the progress)
- [x] [DEV] Hide the "Open In" and "Available Offline" on Streaming mode
- [x] [DEV] Mark the selected cell for downloading file after tap over "Download File" on iPad
- [x] [BUG] App make streaming instead download the video on a downloading file by Download Folder
- [X] [QA] Create test plan
- [X] [QA] validate test plan 
- [ ] [GIT] Merge branch stream_video_files

____

 BUGS & IMPROVEMENTS

- [X] Videos in a downloading folder are streamed https://github.com/owncloud/ios/issues/787#issuecomment-281726386 [FIXED]
- [X] White line on the bottom https://github.com/owncloud/ios/issues/787#issuecomment-282274355 [FIXED]
- [X] Notify users that streaming does not start due to untrusted certificate https://github.com/owncloud/ios/issues/787#issuecomment-282275037 [FIXED]
- [X] https not secure server. All files try to be streamed https://github.com/owncloud/ios/issues/787#issuecomment-282286186 [FIXED]
- [X] https not secure. download folder and files show not-streaming message https://github.com/owncloud/ios/issues/787#issuecomment-282286079 [FIXED]
- [X] Audio does not stop if file is downloaded https://github.com/owncloud/ios/issues/787#issuecomment-282655691

**Comment by hodyroff** [comment]
What is the technical solution? Using the web browser = Safari or something else? If something else which library and are there any other file types supported by this?

**Comment by davivel** [comment]
Both iOS and Android frameworks provide options to play video from an HTTP(S) URL. Should be the path to go, in our opinion. It's the shortest one to have something working soon.

Drawbacks: supported video formats will depend on the system/device (as already happens with downloaded videos); also, cached data are handled by the framework, so reusing the played data to keep the file locally downloaded is unlikely.

We should do a small proof of concept with these APIs.

**Comment by hodyroff** [comment]
Great! If there are any documentation links to the supported file formats on both frameworks, that would be perfect. This sounds great as implementation is using a standard on each framework. Perfect.

**Comment by felixboehm** [comment]
https://github.com/owncloud/core/issues/24480

**Comment by rperezb** [comment]
"If I want to download the file, new "download" option will be added into swipe menu option" just for reference, within the preview view, there is an option to download files too

**Comment by rperezb** [comment]
Currently, once you are previewing a video, no matter if you leave the preview view the file keeps being playing in the background, with the new approach --> streaming, I'd say that this doesn't apply

**Comment by nasli** [comment]
https://github.com/owncloud/ios/issues/787#issuecomment-251597620 @rperezb , but to go to the preview you need to tap over the file, and with the new behavior will start to streaming the video, new option for download file as is already for download folder should be added. And if you tap over the available offline button in the preview the streaming should stop and start downloading the file or other option will be removed this option will is streaming. That is a good point I will add to the AC

**Comment by rperezb** [comment]
@nasli certainly the option download has to be added within the file list view, just pointing out that this option is already included within the preview view for us to analyze the consecuences.

**Comment by rperezb** [comment]
@pmaier1 @felixboehm pending to confirm the acceptance criteria before starting working on this

**Comment by pmaier1** [comment]
@rperezb @nasli @davivel i think this sounds nice and we can confirm this for now. I don't know the further requirements yet but it could be the case that we need to provide an option to parse the stream to an external video player app such as VLC. Will tell you as soon as I know more about this.

**Comment by michaelstingl** [comment]
@pmaier1 The term streaming in this context isn't very precise.

What we can do is a **pretty simple streaming**. For this we require a single mediafile on a webserver, with a special file format, special metadata, and a special data structure. (x264 video within MP4 container) Then, a video player could request single pieces of this mediafile from the webserver to play only those part of the file without the need to download the full mediafile.

Here you can find more information:
https://en.wikipedia.org/wiki/HTTP_Live_Streaming

If you use ffmpeg to create the video file, the following parameters should create a compliant file:

```
ffmpeg -i input.avi -c:v libx264 -crf 22 -c:a libfaac -movflags faststart output.mp4
```
(Source: http://superuser.com/questions/438390/creating-mp4-videos-ready-for-http-streaming)

There are **various other streaming protocols** that require a active streaming server, but this is nothing that can be implemented in ownCloud easily.

Here you can find more information:
http://www.garymcgath.com/streamingprotocols.html

**Comment by butonic** [comment]
not a top 10 SF issue -> blue ticket

**Comment by chscherrer** [comment]
Maybe this would help? https://mobiforge.com/design-development/content-delivery-mobile-devices

**Comment by jesmrec** [comment]
>If new version is available in server and the user taps over the file an alert message will be shown to ask the user whether he wants either to preview the local file or stream the new one. In case he selects stream the new one, the downloaded file will be removed

We have had a little discussion about that. In case of two different versions of the video file (one in server, another one downloaded in mobile client). Which should be the correct behaviour?

- The behaviour described in AC: user can choose whether the remote video is streamed or the local file is played. In case of choosing "remote streaming", the local copy is deleted.
- Download directly the server version (no streaming), because the user had the file already downloaded and we could guess that the user wants to keep the file downloaded as he used to.

@javiergonzper @michaelstingl @pmaier1 @rperezb @davigonz

**Comment by javiergonzper** [comment]
@michaelstingl the streaming can not works with self signed certificates.
I was working on it yesterday the full day and that it is the conclusion.

On iOS9 exist a workaround to make it works but on iOS10 do not works. People reported it to Apple but looks like they will not fix it.
http://stackoverflow.com/questions/38217551/how-can-i-use-an-avplayer-with-https-and-self-signed-server-certificates
https://forums.developer.apple.com/thread/69183

The solution will be detect if the user can make streaming or not (SSL Self Signed) and in the case of not just download the file before play (as we do now) but in the case that the user can make streaming do streaming.

**Comment by hodyroff** [comment]
ok, should be documented. Is Let's encrypt self-signed or official?

**Comment by javiergonzper** [comment]
Yes it should be documented.

What do you mean with "Is Let's encrypt self-signed or official?" ?
Self signed are https with a created by anyone but here we can also include invalid certificates (expired..)

**Comment by hodyroff** [comment]
Does a let's encrypt certificate work = is it accepted by iOS?

**Comment by javiergonzper** [comment]
Exctly. It must to be HTTPS with a right certificate.

**Comment by michaelstingl** [comment]
@hodyroff Everything is fine with let's encrypt if it's deployed properly on the server.

**Comment by michaelstingl** [comment]
> The solution will be detect if the user can make streaming or not (SSL Self Signed) and in the case of not just download the file before play (as we do now) but in the case that the user can make streaming do streaming.

👍

**Comment by michaelstingl** [comment]
> Which of the following do you think it would be better?

@jesmrec @javiergonzper The first way is more intuitive:

> - The behaviour described in AC: user can choose whether the remote video is streamed or the local file is played. In case of choosing "remote streaming", the local copy is deleted.

**Comment by javiergonzper** [comment]
@michaelstingl I am working on the the task about the "New version available". And I think that the behavior of the AC are dangerous:
"If new version is available in server and the user taps over the file an alert message will be shown to ask the user whether he wants either to preview the local file or stream the new one. In case he selects stream the new one, the downloaded file will be removed"

The current behavior it is:
The player play the downloaded file while the new version is downloaded with a progress and a cancel button (same behavior than any other file).

In my opinion this is the best behavior because if the user downloaded the file at the first time it is normal that the user still wanting have the file downloaded.
Following the AC we will delete the file without ask if the user choose streaming. This is very dangerous.
Also if we give the user the possibility of choose streaming without update the old file we will consume the same bandwidth making streaming than the bandwidth that we will consume if we download it.

What do you think?

**Comment by michaelstingl** [comment]
> In my opinion this is the best behavior because if the user downloaded the file at the first time it is normal that the user still wanting have the file downloaded.

I agree

> Following the AC we will delete the file without ask if the user choose streaming. This is very dangerous.

I agree. Adjusting the AC sounds reasonable.

**Comment by jesmrec** [comment]
It is important to know that the video streaming can collide with the file locking of the server. This is, the video file can be locked by the server for a time after being played or interrupted. In this case, actions like move, delete or rename will not work for a time.

This can be avoided by disabling the file locking in server side. This has inconvenients as well, specially if the content is shared.

All of them are corner cases, but i think that are important to take in account.

CC @michaelstingl

**Comment by jesmrec** [comment]
### Bug

Steps

1. Download a folder that contains videos
2. Enter in the folder and tap in a video (not already downloaded)

Current behaviour

Video starts to stream and stops to be downloaded

Expected behaviour

Video can not be streamed. If you tap on it, the download is prioritized but not cancelled

Tested with iPhone 6S Plus v10

CC @javiergonzper

**Comment by jesmrec** [comment]
### Bug

Steps

1. Start the streaming
2. Rotate the device

Current behaviour

in the bottom of the video is shown a white line

Expected behaviour

No white line

Tested with iPhone6 iOS 10.2.1

**Comment by jesmrec** [comment]
### Enhacement

In case of certificate is not trusted, the file is not streamed and starts to be downloaded. Maybe a nice option to notify the user of this behaviour.

**Comment by michaelstingl** [comment]
> Maybe a nice option to notify the user of this behaviour.

I also think user notification/feedback would help here.

**Comment by jesmrec** [comment]
### Bug

Steps

1. In a non-trusted server, set a folder that contains videos as av. offline, or download folder
2. Enter in the folder and tap on a video while it is being downloaded

Current behaviour

Message about streaming not posible is displayed

Expected behaviour

The file is already being dowloaded, so the message should not be displayed

Tested with iPadAir v10, iPhone6 v10

CC @javiergonzper

**Comment by jesmrec** [comment]
### Bug

Steps

1. In a non-trusted server, tap on a file (not a video)


Current behaviour

Message about streaming not posible is displayed

Expected behaviour

The file is downloaded.

Tested with iPadAir v10, iPhone6 v10

CC @javiergonzper

**Comment by jesmrec** [comment]
### Bug

Steps

1. In an iPad, start to stream a video
2. While the streaming is running, download the video

Current Behaviour

Streaming is stopped, audio keeps on and video starts to download

Expected behaviour

Video can not be downloaded if it is being streamed.

Tested with iPad v10

CC @javiergonzper

**Comment by jesmrec** [comment]
all bugs fixed. 

Approved

**Comment by wouterbudding** [comment]
What me helped, was the comment of https://github.com/michaelstingl , commented on Nov 8, 2016. I wanted to create an movie/export of Zoneminder stills:

`cat {00610..00735}-capture.jpg | ffmpeg -f image2pipe -framerate 15 -i - -s 1920x1080 -crf 0 -an 
 out.mp4`

but the movie didnt start in the OC iOS app. But with this command, it did

`cat {00610..00735}-capture.jpg | ffmpeg -f image2pipe -framerate 15 -i - -s 1920x1080 -crf 1 -c:a libfaac -movflags faststart -c:v libx264 out.mp4`

and I believe removing `-an` and adding `-c:a libfaac` plus `-crf 1` instead of `-crf 0` , did help.
