### ISSUE TITLE
[3.5.3] Release a new version 

### ISSUE THREAD

**Issue by nasli** [owncloud/ios#815]
Release a new version
## TASKS:
- [x] [GIT] Create branch release_3.5.3 (freeze the code)
- [x] [GIT] Create branch library release_ios_app_3.5.3 (freeze the code)
- [x] [DIS] Update changelog ios app
- [x] [DIS] Update changelog ios library app
- [x] [DEV] Update version number 3.5.3
- [x] [DEV] Update readme number version app and library
- [x] [DEV] Update year https://github.com/owncloud/ios/issues/815#issuecomment-272432774
- [x] [DEV] Remove support iOS 8
- [X] [QA] Design Test plan @jesmrec
- [X] [QA] Regression Test plan @jesmrec
- [x] [DIS] Update screenshots.
- [x] [DIS] Release to appstore
- [x] [GIT] Merge branch release_3.5.3
- [x] [GIT] Merge branch release_ios_app_3.5.3
- [x] [GIT] Create tag and sign it
- [x] [DEV] Add license of Gif library to third party file
_____

BUGS & IMPROVEMENTS

- [X] App freezes when a folder is browsed twice https://github.com/owncloud/ios/issues/815#issuecomment-274755680 [FIXED] https://github.com/owncloud/ios/pull/832
- [X] Message when no quota is available in server https://github.com/owncloud/ios/issues/815#issuecomment-274756487 [FIXED]
- [X] Touch id disabled when enforced passcode is changed https://github.com/owncloud/ios/issues/815#issuecomment-276425155 [FIXED]
- [X] Passcode is not updated https://github.com/owncloud/ios/issues/815#issuecomment-276703352 [FIXED]
- [x]  UI Improvements in passcode 
- [X] Share with oC in SAML https://github.com/owncloud/ios/issues/815#issuecomment-276951703 [FIXED]
- [X] Share with oC in SAML error message not localized https://github.com/owncloud/ios/issues/815#issuecomment-276951703 [FIXED]
- [X] Maintenance mode in expiration of SAML sessions https://github.com/owncloud/ios/issues/815#issuecomment-277610868 [FIXED] Please, check also renew expired session with different username -> [CHECKED]
- [x] Document provider https://github.com/owncloud/ios/issues/815#issuecomment-277611771  [FIXED]

**Comment by jesmrec** [comment]
Year updating:

`//app year
#define k_year 2016`

**Comment by jesmrec** [comment]
###Bug

Steps

1. Browse into a folder
2. Browse back
3. Browse again to the same folder

or

1. Download a folder / Set as available offline a folder
2. Browse into the folder

Current behaviour

Spinner "Loading" is displayed forever. App freezes. 
It seems to be the second time the folder is browsed.

Expected behaviour

Usual browsing

Checked with SAML servers and basic auth servers

iOS 9, iOS10
Server 9.1 and 10

**Comment by jesmrec** [comment]
Improvement:

The message in uploads view when there is no available quota in server is currently:

`Not enough free space`

The message:

`Not enough space in the account`

clarifies better the situation, so that the storage lack is in server side.

**Comment by jesmrec** [comment]
### Bug

Steps

1. Enforce passcode in a device with touch id
2. Go to settings view
3. Enable "Touch id"
4. Change Passcode Lock -> Set a new passcode

Current behaviour

Touch id is disabled

Expected behaviour

Touch id remains enabled

Tested with

iPhone  6S Plus v10.1.1
Server version 10.0

CC @nasli

**Comment by jesmrec** [comment]
### Bug

1. Enforce passcode -> set 1111
2. In settings view, change passcode lock -> set 2222 as new passcode

Current behaviour

1111 is the correct passcode

Expected behaviour

2222 is the correct passcode

This bug only happens from https://github.com/owncloud/ios/commit/6208f673b9433763fced6b63cbe5c295029a457d`

Testes with iPad Air v9, iPhone 6S Plus v10.1.1

CC @nasli

**Comment by jesmrec** [comment]
### Bug

Steps

1. Log in a SAML account
2. From an external app (for example, Photos), try to share content with oC

Current behaviour

Always is received "not possible connect to the server"

Expected behaviour

Content is uploaded to oC

Server 9.1.4
Tested with iPhone 6S Plus v10.1.1 iPad Air 9.3

CC @nasli

**Comment by jesmrec** [comment]
### Bug

Steps

1. Set server in maintenance mode
2. Let session expires
3. Input credentials

Current behaviour

First is displayed `The entered user does not match the user of this account`. After that, `The server is in maintenance mode`

Expected behaviour

Only the message The server is in maintenance mode`

Tested with iPad v9.3, iPhone &S Plus v10

**Comment by jesmrec** [comment]
This problem https://github.com/owncloud/ios/issues/815#issuecomment-276951703 also happens if we try to open an oC file with an external app using the document provider.

**Comment by nasli** [comment]
https://github.com/owncloud/ios/issues/815#issuecomment-277611771
Looks like same error but are different and this one is not a regression

**Comment by jesmrec** [comment]
All bugs fixed. QA Approved.

CC @javiergonzper @nasli
