### ISSUE TITLE
[3.6.0] Release a new version

### ISSUE THREAD

**Issue by nasli** [owncloud/ios#837]
Release a new version
## TASKS:
- [x] [GIT] Create branch release_3.6.0 (freeze the code)
- [x] [GIT] Create branch library release_2.1.0_library (freeze the code)
- [x] [DIS] Update changelog ios app
- [x] [DEV] Update version number
- [x] [DEV] Update readme number version app and library
- [x] [DOC] Update branch to master in CONTRIBUTING.md
- [X] [QA] Design Test plan
- [X] [QA] Regression Test  @jesmrec @davigonz 
- [x] [DIS] Update screenshots. 
- [X] [DIS] Create itunes new version
- [x] [DIS] Upload new ipa to appstore
- [x] [GIT] Merge branch release
- [x] [GIT] Merge branch library release
- [x] [GIT] Create tag and sign it
- [X] Update share icon https://github.com/owncloud/ios/issues/862 

PR: https://github.com/owncloud/ios/pull/890
PR library: https://github.com/owncloud/ios-library/pull/156
_____

BUGS & IMPROVEMENTS

- [X] (3) Custom groups name https://github.com/owncloud/ios/issues/883  [FIXED] 
- [X] (4) Cancel in SAML expiration https://github.com/owncloud/ios/issues/837#issuecomment-298658585   [FIXED]
- [x] (5) SSO webview https://github.com/owncloud/ios/issues/837#issuecomment-301743023 [FIXED in https://github.com/owncloud/ios/pull/888 ]
- [x] (6) Message in login view https://github.com/owncloud/ios/issues/837#issuecomment-302643231 [DONE]
- [X] (7) Update app version https://github.com/owncloud/ios/issues/837#issuecomment-302677423     [DONE]
- [X] (8) Cancelling uploads makes crashes https://github.com/owncloud/ios/issues/837#issuecomment-302681229 [FIXED]
- [X] (9) Audio does not stop in video streamed https://github.com/owncloud/ios/issues/837#issuecomment-302694010 [FIXED]
- [X] (10) Crash when move in an inexistent folder https://github.com/owncloud/ios/issues/837#issuecomment-302705726 [FIXED]
- [X] (11) Crash when moving to Files section after switching between different accounts https://github.com/owncloud/ios/issues/837#issuecomment-303025289 -> https://github.com/owncloud/ios/issues/884
- [X] (12) Spinner when passcode/touch id https://github.com/owncloud/ios/issues/837#issuecomment-303033782 [FIXED]
- [x] (13) Pop up in expired session - create public link https://github.com/owncloud/ios/issues/837#issuecomment-303069436 [FIXED]
- [x] (14) Repeated download view https://github.com/owncloud/ios/issues/837#issuecomment-303092399 [FIXED]

**Comment by jesmrec** [comment]
What do you think about using 3.6.0 for this version instead of 3.5.4? in order to be more congruent with the other clients: only using the sub-subversion number for bug fixing or minor versions .

CC @nasli @davivel @michaelstingl @davigonz

**Comment by michaelstingl** [comment]
Yes, https://github.com/owncloud/ios/milestone/14 is a bigger one. I like the idea.

**Comment by davivel** [comment]
I think that, for planning purposes, makes more sense update always, at least, the minor version (second digit). If for any reason we have to release sooner with only fixes we can then "step back" and update only the patch number (third digit) instead.

**Comment by jesmrec** [comment]
### Bug

1. Start a session in a SAML server with multiaccount (no matter how many accounts are attached)
2. Wait until session expires

Current behaviour

"Cancel" button does not make vanishing the login view. No longer options but inputing credentials 

Expected behaviour

"Cancel" allows the user to go to settings view. Another option is preventing users to cancel the login view (same behaviour as migration).

Tested with iOS10.

**Comment by jesmrec** [comment]
### Bug

Open the app and enter in a SAML server with SSO

Current: webview to type credentials does not appear in a long time
Expected: webview appears

SAML server v10.0
iPhone 6Plus v10, iPad Air v9

**Comment by jesmrec** [comment]
### (6) Improvement

1. Login with an user
2. Create a new account with the same user

Current: pop-up `The entered user already exists`
Expected: message between password and button

iOS10, server10RC3

**Comment by jesmrec** [comment]
(7) Bug

In settings view appears 3.5.3 as version. It should be 3.6.0

**Comment by jesmrec** [comment]
### (8) Bug

1. Upload a photo or video
2. When it is being uploaded, cancel it

Current: crash
Expected: cancelled upload

iPadAir v9.3.5 
Server 10.0.1RC3 (no saml)

**Comment by jesmrec** [comment]
### (9) Bug 

1. Stream a video in a tablet
2. Browse in files view and open other file

Current: Audio of the video continues 
Expected: Other file is opened on the right side, video should stop.

iPadAir v9.3.5 
Server 10.0.1RC3 (no saml)

**Comment by jesmrec** [comment]
### (10) Bug

1. On a folder, select move
2. Select a target folder without submitting
3. In web, remove the target folder
4. In app, submit the selection of 2.

Current: Crash 
Expected: Error message

iPadAir v9.3.5 
Server 10.0.1RC3 (no saml)

**Comment by davigonz** [comment]
### (11) Bug 

**Steps:** 

1. Login with an user.

2. Go to Settings and press Add new account button.

3. Login with other user.

4. Switch to the just added account. 

5. Go to Files view.

6. Go back to Settings, switch to the account created firstly. 

7. Go to Files view.

**Current behavior:** 

- Crash

**Expected behavior:** 

- When tapping on the Files section, it should be shown.

Tested with iPhone 6S Plus 9.3.2
Server v10.0.1RC3

**Comment by jesmrec** [comment]
@davigonz this is already reported in a separate issue: https://github.com/owncloud/ios/issues/884

**Comment by davigonz** [comment]
@jesmrec 

> this is already reported in a separate issue: https://github.com/owncloud/ios/issues/884

Ok, I haven't seen it in the current milestone, is not going to be fixed for this release? It seems kind of important

**Comment by jesmrec** [comment]
it is pretty annoying when you use multiaccount, but it is not a regression. this is in @davivel or @nasli 's hands.

**Comment by jesmrec** [comment]
### (12) Bug

1. Enable passcode or touch id
2. Download a huge file
3. Close the app and open it again (not necessary waiting to background)
4. Enter passcode/touch id

Current: Spinner forever 
Expected: Spinner disappears

iPhone6Plus v10.1.1
Server 10.0.1RC3 with SAML

**Comment by jesmrec** [comment]
### (13) Bug

1. In a SAML server, wait until session expires
2. Create a public link

Current: Pop up is shown with the expiration session message
Expected: No pop up. Only message in login view

iPhone6SPlus v9.3.2
Server 10.0.1RC3 with SAML

**Comment by jesmrec** [comment]
Bug (3) https://github.com/owncloud/ios/issues/883 is not fixed with the commit `34eacc9b8edc56a30d87fb18f79d084ace2adf78`

**Comment by davivel** [comment]
(14) Bug

1. Enable passcode or touch id
2. Download a huge file
3. Close the app and open it again (not necessary waiting to background)
4. Enter passcode/touch id
5. Tap on 'Back' to see the list of files

Current: A second view with the download in progress (stopped) is shown. You need to click 'Back' again to get to the list of files.
Expected: The list of files is shown

iPhone6Plus v10.1.1
Server 10.0.1RC4 with or without SAML

**Comment by davivel** [comment]
> Bug (3) #883 is not fixed within the commit 34eacc9b8edc56a30d87fb18f79d084ace2adf78

What? No way :(

**Comment by jesmrec** [comment]
### (15) Bug

1. Enable passcode or touch id
2. Download a huge file
3. Close the app and open it again (not necessary waiting to background)
4. Enter passcode/touch id
5. Tap on 'Back' to see the list of files

Current: A second view with the download in progress (stopped) is shown. You need to click 'Back' again to get to the list of files.
Expected: The list of files is shown

iPhone6Plus v10.1.1
Server 10.0.1RC4 with or without SAML

**Comment by davivel** [comment]
@jesmrec , about (4), the 'cancel' button is now inaccessible for SAML servers.

**Comment by jesmrec** [comment]
all fixed, version approved.

**Comment by nasli** [comment]
Next release will be available in AppStore in a couple of days
