### ISSUE TITLE
Multiple Share Links

### ISSUE THREAD

**Issue by jesmrec** [owncloud/ios#866]
Multiple share links is a new feature in oC10, that allows to create more than one public link over the same file/folder.

Current behaviour:

- The iOS mobile app only supports one public link. 
- The behaviour right now is showing the last one of the public links created on the server side. 
- If the link is edited in the iOS app, the name is removed from the link in server side  -> https://github.com/owncloud/core/issues/27622
- If the link is removed from the device, the previous one is displayed

It will require some actions:

- [x] UI changes to adapt to the new feature. As proposal, they can be handled in the same way as the internal sharing: "Add public links" button (or "+" symbol regarding https://github.com/owncloud/ios/pull/859) with an option to edit the public link options (name, allow editing if folder, expiration, password)
- [x] Update wordings "Public link" -> "Public Links", "Share with users.." -> "Users an groups"
- [x] Update  shareObj and parser in library
- [x] Update DB with new name parameter
- [x] Update capabilities with the new parameter "files_sharing" > "multiple"  in library (see https://github.com/owncloud/core/issues/27622 )
- [x] Update db for capability
- [X] Replace "i" icon in sharees cell with a disclosure - [I rather to keep it with the information icon that for iOS means new view where the user can edit, the disclosure icon it is used to show a navigation]
- [x] New public link cell will show the name of the link if exist and a disclosure to navigate to details
- [x] New button "public link icon" in public link cell that will allow share the link 
- [x] Move current settings options for public links to new view as share users edit options
- [x] Add a new field related that allow set up the link name. (set file name as a default)
- [x] Warning about public links, new parameter k_warning_sharing_public_link https://github.com/owncloud/enterprise/issues/1914
- [x] Get correct share link and show share activity view
- [X] Create new methods in library to support update new name parameter (deprecate old one) 
- [X] Create new methods in library to support create new links with all options (deprecate old one)
- [x] Add new library tests for the new methods
- [X] Handle the different cases when updating the public share password, allow uploads, name, expiration
- [x] Grant that password is required when server enforces it
- [x] Grant that expiration time is required when server enforces it
- [x] Ensure that expiration date is shown by default when server set up
- [x] Handle errors
- [X] Grant that share link not shown if cap is disabled
- [X] Enable or disable multiple links support depending on the corresponding capability (see https://github.com/owncloud/core/issues/27622 )
- [X] Hide new parameter name in create and update view for server minor 10 or not multiple cap enabled
- [X] Always show Warning about public share link with message "Anyone with the link has access to the file/folder"  with gray color https://github.com/owncloud/core/pull/27844/files
- [x] Shared public links view. Should all links for the same content be displayed here? or only one for file/folder? --> all links should be displayed in shared links view.
- [X] For all the things: ** grant compatibility with server <= 9.x **
- [X] Confirm remove link
- [x] Keyboards UI 
- [x] Clean unneeded code of the previous sharing version
- [x] [QA] Design test plan @jesmrec
- [ ] [QA] Validate test plan [WIP] @jesmrec

_____

BUGS & IMPROVEMENTS

- [X] (1) Shares not displayed https://github.com/owncloud/ios/issues/866#issuecomment-301397125 [FIXED] @nasli
- [X] (2) Allow uploads unreachable https://github.com/owncloud/ios/issues/866#issuecomment-301470426 [FIXED] @nasli
- [X] (3) Allow uploads can not be edited https://github.com/owncloud/ios/issues/866#issuecomment-301471382 [FIXED] @nasli
- [X] (4) Special characters in link name https://github.com/owncloud/ios/issues/866#issuecomment-301756902 [FIXED]  @nasli
- [X] (5) Password not reset https://github.com/owncloud/ios/issues/866#issuecomment-301795055 [FIXED] @nasli
- [X] (6) Date picker with selected date https://github.com/owncloud/ios/issues/866#issuecomment-301802983 [FIXED] @nasli
- [X] (7) Padding between expiration field and warning message https://github.com/owncloud/ios/issues/866#issuecomment-301814553 [WON'T FIX, future improvement maybe] @nasli
- [X] (8) Edit public link with password enforced https://github.com/owncloud/ios/issues/866#issuecomment-301816933 [FIXED] @nasli
- [X] (9) Warning is swipped and make the app crashes https://github.com/owncloud/ios/issues/866#issuecomment-301818149 [FIXED] @nasli
- [X] (10) Shared links display https://github.com/owncloud/ios/issues/866#issuecomment-301823697 [WON'T FIX, out of the scope the share link view tab]  @nasli
- [X] (11) UX in password enabling https://github.com/owncloud/ios/issues/866#issuecomment-302012004 [WON'T FIX, here]
- [X] (12) Become first response link name [WON'T FIX] @nasli  https://github.com/owncloud/ios/issues/866#issuecomment-302033705
- [X] (13) Expiration date and view refresh  https://github.com/owncloud/ios/issues/866#issuecomment-302051412 [FIXED] 
- [X] (14) Allow public uploads capability https://github.com/owncloud/ios/issues/866#issuecomment-302055894 [WONT'T FIX, core issue reported https://github.com/owncloud/core/issues/27922 ]
- [X] (15) Removal message in oC9 https://github.com/owncloud/ios/issues/866#issuecomment-302056162 [WON'T FIX, it is used same approach that in the server]
- [X] (16) Connection error message appears twice https://github.com/owncloud/ios/issues/866#issuecomment-302058975 [WONT'T FIX, here]
- [X] (17) Delete in oC 9 https://github.com/owncloud/ios/issues/866#issuecomment-302059955 [FIXED] 

Related on Android https://github.com/owncloud/android/issues/1928

PR: https://github.com/owncloud/ios/pull/887
library PR: https://github.com/owncloud/ios-library/pull/155

Fixes: #861

**Comment by mmattel** [comment]
Because the current behaviour of the App affects also the server side, I set this to bug.

**Comment by SamuAlfageme** [comment]
> If the link is edited in the iOS app, the name is removed from the link in server side.

https://github.com/owncloud/core/issues/27517

**Comment by jesmrec** [comment]
@mmattel as @SamuAlfageme has written, the problem is in server side and not in apps. So, it's not a bug in this side.

**Comment by mmattel** [comment]
ok thx, fix in core is https://github.com/owncloud/core/pull/27529

**Comment by nasli** [comment]
Updated definition in the top.

**Comment by michaelstingl** [comment]
Slightly changed plan:

We will get a capability for "Warning about public links" on the server side. Then we don't need a ownBrander option. (see owncloud/enterprise#1914 (comment))

**Comment by jesmrec** [comment]
Starting QA stage

**Comment by jesmrec** [comment]
### Bug (1)

Shares are not displayed. Neither internal, not public. 

Create a share in the app

Current behaviour: Shares are created (appear in server web UI), but it is not displayed in app. 

Expected behaviour: Shares displayed

No mater if the server is SAML or basic auth.

Tested with iPhone 6Plus v10

**Comment by jesmrec** [comment]
### Improvement (2)

1. Create a public link on a folder
2. Tap on the name of the link to edit it.

Current behaviour

Allow uploads option is unreachable behind the keyboard, at least you tap on "Done", or enable other option (Password or Expiration)

Expected behaviour

Allow uploads is reachable

iphone6 Plus v10

**Comment by jesmrec** [comment]
### Bug (3)

1. Create a public link on a folder and save it
2. Tap on the link to edit it
3. Enable "Allow uploads" and tap on "Done"

Current behaviour

`Wrong or no update parameter given`

Expected behaviour

Option enabled 

iphone6 Plus v10

**Comment by jesmrec** [comment]
### (4) Bug

1. Create a public link with link name: @#$
2. Save

Current: The name link in the list is `@`
Expected: The name link in the list is `@#$`

Server v10 SAML
iPhone6 Plus v10

**Comment by jesmrec** [comment]
### (5) Bug

1. Create a public link 
2. Enable `Password`switch
3. Type a password
4. Disable `Password` switch

Current:  Password appears (black points) with the switch disabled
Expected: With the switch disabled appears the hint `Choose a password`

Server v10 SAML
iPhone6 Plus v10

**Comment by jesmrec** [comment]
### (6) Improvement 

1. Create a public link and set an expiration date
2. Tap on the expiration date in order to edit it

Current behaviour

In the date picker appears today date as default

Expected behaviour

In the date picker appears the selected as default

iphone6 Plus v10
Server v10 SAML

**Comment by jesmrec** [comment]
### (7) Improvement 

Please, set a little padding between the expiration field and the warning of enforced expiration. They are too close:

![screen shot 2017-05-16 at 17 12 12](https://cloud.githubusercontent.com/assets/14894746/26113505/ffd06c68-3a5a-11e7-8bc3-b115dc673409.png)

**Comment by jesmrec** [comment]
### (8) Bug

1. Enforce password in server 
2. Create a public link with mandatory password and save it
3. Edit the link
4. Tap on `Done`, no matter if you edit some field or not

Current:  Ask for password, but password was set in creation
Expected: Public link can be edit.

Server v10 SAML
iPhone6 Plus v10

**Comment by jesmrec** [comment]
### (8) Bug

1. Swipe left the warning `Anyone with the link has access to the file/folder` -> Appears `Delete`
2. Tap on `Delete`

Current:  App crashes
Expected: Warning can not be swipped

Server v10 SAML
iPhone6 Plus v10

**Comment by jesmrec** [comment]
### (10) Improvement 

the shared links view shows all the links as expected. But, links over the same content are not different. Maybe the should be shown once per item, or distinguish using the link name instead. What do you think about? @nasli @davivel @davigonz

**Comment by nasli** [comment]
(10) Out of the scope of this US. We can consider it for future to update the share link tab view.

**Comment by jesmrec** [comment]
### (11) Improvement  

When the password with is enabled, nothing happens. It would be nicer if the enabling raises the keyboard and set the cursor in the edit field, avoiding the user to tap on the field.

**Comment by davigonz** [comment]
### (12) Improvement

I've copied the next improvement from the Android issue

When the Password switch is enabled, the keyboard should be displayed to avoid the user tapping on the field to input the password. The same would be for Link name but in this case, it should be displayed just after the view is opened.

**Comment by nasli** [comment]
(12) I would not suggest that, the links has a name by default, an the normal use case is not change the name, if the user want to change it is allowed

**Comment by jesmrec** [comment]
@nasli relaterd with improvement (6) https://github.com/owncloud/ios/issues/866#issuecomment-301802983, when the expiration is not set in the server, the issue keeps on happening

**Comment by nasli** [comment]
If there is not a bug, please open as new issue an all new UX share improvements will take care for the end of release or next releases.

**Comment by davivel** [comment]
I'd rather to let the full tests finish, and then move to new issues all that makes sense to move.

**Comment by jesmrec** [comment]
i will post all the improvements although they are not going to be developed right now, so they are in the scope of the current issue.

**Comment by davigonz** [comment]
### (13) Bug 

**Steps:** 

1. Create a link share.

2. Set default date and enforced it from the web.

3. Edit the link share just created.

**Current behaviour:** 

- When tapping on the expiration date field, nothing happens.

- When pressing the done button, edit link share view is not closed. 

**Expected behaviour:** 

- When tapping on the expiration date field, the calendar to set the date should be shown.

- When pressing the done button, edit link share view should be closed.

Tested with iPhone 6S Plus 9.3.2
Server v10.0.1RC1

**Comment by jesmrec** [comment]
### (14) Bug

1. in server, disable the capability `Allow public uploads`
2. In app, refresh capabilities, create a public link on a folder and save it

Current:  A pop-up is shown: `Public upload disabled by the administrator`
Expected: Public link created 

Server v10 SAML
iPad 9.3.5

**Comment by davigonz** [comment]
### (15) Bug 

**Steps:** 

1. Create a link share.

2. Swipe to delete the link share just created.

3. Unexpected delete confirmation message.

**Current behavior:** 

- Message to confirm the deletion is: "Remove link, **! Delete (null)**"

**Expected behavior:** 

- Something like "Remove link, **Are you sure you want to delete it?"**

Tested with iPhone 6S Plus 9.3.2
Server v9.1.4

**Comment by davigonz** [comment]
### (16) Improvement 

**Steps:**

1. Switch internet connection off.

2. Press button to create share link.

3. Press done button.

**Current behavior:** 

- Internet connection error message is shown twice. After pressing OK in the first error message, it appears again.

**Expected behavior:** 

- Internet connection error message is shown once.

Tested with iPhone 6S Plus 9.3.2
Server  v10.0.1RC1

**Comment by jesmrec** [comment]
(17) 

1. Delete a public link by swipping:

- oc10: message is `! Delete`
- oc9 < : message is `! Delete (null)

they should be the same, at least not showing the (null)

**Comment by nasli** [comment]
(15) Edited to a bug, null should not appear, but the wording is the same that in the server.

**Comment by nasli** [comment]
@davigonz Reedited (15), Improvement a won't fix, on the 17 @jesmrec contemplate the bug that shown "null"

**Comment by jesmrec** [comment]
All fixed. Approved.
