### ISSUE TITLE
iOS 11

### ISSUE THREAD

**Issue by nasli** [owncloud/ios#905]
Notes to take care:

- [ ] Files app, ~~seem not available for 3rd party yet on first dev beta~~ [WIP]
- [x] Compiled with Xcode9 without issues
- [x] Check changes in Swift4
- [x] Upgrade system (10.12.4 or later) and Xcode9, in all environments 
- [x] Update ownBrander

___

iOS11.0 - iPad Air 2 Bling . iPhone6S Plus

- [X] Blanks over lists https://github.com/owncloud/ios/issues/905#issuecomment-313660230 [FIXED]
- [X] Background for instant uploads https://github.com/owncloud/ios/issues/905#issuecomment-313676014 [FIXED]
- [X] Double touch id https://github.com/owncloud/ios/issues/905#issuecomment-313678323 [FIXED] Fix https://github.com/owncloud/ios/issues/939
- [ ] *.HEIC images https://github.com/owncloud/ios/issues/933
- [x] Behaviour in opening files https://github.com/owncloud/ios/issues/947
- [ ] Support Files app https://github.com/owncloud/ios/issues/941 [WIP] @pablocarmu 
- [x] Crash when building with XCode9 https://github.com/owncloud/ios/issues/905#issuecomment-344351651 [CAN NOT REPRODUCE]
- [X] Files view in landscape https://github.com/owncloud/ios/issues/905#issuecomment-352774104 [FIXED]
- [ ] Save documents https://github.com/owncloud/ios/issues/947

Enhancements:

- [ ] Drag & Drop https://github.com/owncloud/ios/issues/925
- [ ] Multiframe https://github.com/owncloud/ios/issues/924

PR: https://github.com/owncloud/ios/pull/959

**Comment by jesmrec** [comment]
First approach to ownCloud app in iOS 11:

iOS11 Beta 2 (15A5304j)
iPad Air 2 Bling

**Comment by jesmrec** [comment]
We have blanks over the file list and also in settings view:

![screen shot 2017-07-07 at 13 45 32](https://user-images.githubusercontent.com/14894746/27956598-dece7a76-631a-11e7-8653-05de08c0f534.png)

![screen shot 2017-07-07 at 13 45 46](https://user-images.githubusercontent.com/14894746/27956604-e19ce1f2-631a-11e7-94a1-94b9c761d311.png)

**Comment by jesmrec** [comment]
The app is not handled with location services, making instant uploads not to work in background.

1. Install the app from scratch
2. Enable instant uploads Photos and Videos, and also Background mode

Current: User is not asked for accept using "location services". App does not appear in Settings -> Location Services. If the app is killed, and after that reopened, the option "Background" is disabled.

**Comment by jesmrec** [comment]
1. Enable touch id
2. Kill the app
3. Open the app

Current: touch id is shown twice:

![jul-07-2017 15-16-19](https://user-images.githubusercontent.com/14894746/27959370-7251dd4a-6327-11e7-8feb-83b630556e30.gif)

**Comment by davivel** [comment]
@michaelstingl , Apple will show the new iPhone on Sept, 12th. It is probable that final version of iOS 11 is ready that day. We should complete the testing of the app with a newer version of iOS 11 beta and prepare a minor release with bug fixing after the current one.

Agree?

**Comment by michaelstingl** [comment]
> Agree?

@davivel Yes, fully agree. I was thinking the same, but you wrote it first 😉

**Comment by jesmrec** [comment]
We have to pay attention to the login process in iOS11. Right now, with the beta8 released, the app crashes after tapping on `Connect` button (checked in iPad Air) with the `oauth_support` branch. Tracking this issue and maybe we should face it in that branch.

**Comment by jesmrec** [comment]
Checked the iOS11 beta10. Same status.

**Comment by jesmrec** [comment]
Golden Master released. All reports from this moment will be related with that version.

**Comment by jesmrec** [comment]
It is noticeable that the 3.6.2 iOS app (latest stable) works pretty well on iOS11. Any of the previoulsy reported bugs happens in that version, and only https://github.com/owncloud/enterprise/issues/2264 is reproduced.

**Comment by jesmrec** [comment]
Related with https://github.com/owncloud/ios/issues/947, we have noticed that some external apps does not show oC as an option to save **NEW** content. Opening existing content is posible. It should be a matter of FilesApp, pending to be checked after checking and first testing approach.

**Comment by jesmrec** [comment]
### BUG (high)

1.- Install the app after building it with XCode9, using the `master`branch
2.- Enter credentials OAuth2 or basic

Current: crash
Expected: no crash

iPhone 6S Plus with iOS11. Server v10

NOTE: Crash does not happen if the app is built with XCode8 and installed in iOS11

**Comment by martinschilliger** [comment]
I see this error message in console:
`Owncloud iOs Client[11371:639679] (setCredentials)Error Code: 0 (0 = success)
Could not cast value of type 'Swift._ContiguousArrayStorage<__ObjC.FileDto>' (0x11168fe40) to 'NSMutableArray' (0x110f09ea0).`

And it points me to the [ManageFiles.swift](https://github.com/owncloud/ios/blob/fd8e4114b87e64fb2f50eb1b5973d70eec99826c/Owncloud%20iOs%20Client/Tabs/FileTab/ManageFiles.swift#L34) file.

Is this the same error? I don't even know where to start debug. Also on XCode 9 with iOS 11/iOS 10.

**Comment by jesmrec** [comment]
@martinschilliger could you check with `ios_11_support`branch?

**Comment by martinschilliger** [comment]
@jesmrec: Thank you! I don't know why I didn't try the obvious… 😏

**Comment by imclean** [comment]
@martinschilliger To fix ManageFiles.swift you will need to change to this:
`
func storeListOfFiles(_ listOfFiles: [FileDto] , forFileId fileId: Int, andUser user: UserDto) {
        
        //Change the filePath from the library to our db format
        
        for currentFile:FileDto in listOfFiles {
            
            currentFile.filePath = UtilsUrls.getFilePathOnDBByFilePath(onFileDto: currentFile.filePath, andUser:user)
        }
        
        
        ManageFilesDB.insertManyFiles((listOfFiles as NSArray).mutableCopy() as! NSMutableArray, ofFileId: fileId, andUser: user)
        
    }
`

**Comment by jesmrec** [comment]
### BUG 

1.- Open file list
2.- Set the device in landscape

Current:

View does not fill all the screen. Only half screen

Expected:

View fills all the screen

Tested with iPhone6SPlus v11
