### ISSUE TITLE
[3.6.2] New release

### ISSUE THREAD

**Issue by nasli** [owncloud/ios#907]
Release a new version
## TASKS:
- [x]  [GIT] Create branch release_3.6.2 (freeze the code)
- [x] [DIS] Update changelog ios app
- [x] [DEV] Update version number
- [x] [DEV] Update readme number version app manual
- [x] [QA] Smoke test & changes form 3.6.0-3.6.1
- [x] [DIS] Update screenshots. 
- [x] [DIS] Create itunes new version
- [x] [DIS] Upload new ipa to appstore
- [ ] [GIT] Merge branch release
- [ ] [GIT] Merge branch library release
- [ ] [GIT] Create tag and sign it

PR: https://github.com/owncloud/ios/pull/908

BUGS:

- [X] (1) Password not correctly edited https://github.com/owncloud/ios/issues/907#issuecomment-307383106 [FIXED]

**Comment by jesmrec** [comment]
Checks:

- [ ] Install from scratch
- [ ] Create & edit public links
- [ ] Get public links
- [ ] Private link (all devices&iOS)
- [ ] Smoke test
- [ ] Upgrade from 3.6.0
- [ ] Upgrade from 3.6.1

**Comment by jesmrec** [comment]
### Bug

Steps:

1.- Create a public link
2.- Edit the link changing the password (for example: "asd"

Current: Password is not correctly edited. Link is not accesible. Password sent is: %61%73%64
Expected: Correctly edited

Tested with iPad Air v10, iPhone 6Plus v10.1.1
