### ISSUE TITLE
[3.7.0] Release new version

### ISSUE THREAD

**Issue by jesmrec** [owncloud/ios#923]
#Release a new version
## TASKS:
- [x] [GIT] Create branch release_3.7.0 (freeze the code)
- [x] [GIT] Create branch library release_2.2.0_library (freeze the code)
- [X] [DEV] Remove private link icon in share view, Wait for https://github.com/owncloud/core/issues/28984 for a proper implementation 
- [x] [DIS] Update changelog ios app
- [x] [DEV] Update version number
- [x] [DEV] Update readme number version app and library, xcode version
- [x] [DEV] Update third party file
- [x] [DEV] Get latest translations from master
- [X] [QA] Design Test plan @jesmrec
- [X] [QA] Regression Test  @jesmrec 
- [X] ~~[DIS] Update screenshots.~~
- [x] [DIS] Create itunes new version
- [x] [DIS] Upload new ipa to appstore
- [x] [GIT] Merge branch release
- [x] [GIT] Merge branch library release
- [x] [GIT] Create tag and sign it
- [x] Ping to publish in social media

PR: https://github.com/owncloud/ios/pull/958
PR library: https://github.com/owncloud/ios-library/pull/168
_____

BUGS 
- [X] (0) [Bug] Crash when switch account https://github.com/owncloud/ios/issues/884 Not a regression, PR:https://github.com/owncloud/ios/pull/963 Lib PR: https://github.com/owncloud/ios-library/pull/171 [FIXED] 
- [X] Bug duplicated accounts [Fixed]  PR: #976, SAML will be reviewed later 
- [X] (1) [Bug] copying share link crashes with 8.2.x server Not a regression, [FIXED] PR: https://github.com/owncloud/ios/pull/969
- [X] (2) [Bugs] https://github.com/owncloud/ios/pull/919#issuecomment-341401365 Review with latest OAuth server update [FIXED] PR: https://github.com/owncloud/ios/pull/983 more improvements will be handle later
- [X] (3) [Bug] Credentials skipped when tried to login twice with the same username https://github.com/owncloud/ios/issues/923#issuecomment-343838629
 [FIXED] PR: #962 
- [X] (4) [Bug] Credentials skipped when editing credentials https://github.com/owncloud/ios/issues/923#issuecomment-343860193 
[CHECK https://github.com/owncloud/ios/issues/923#issuecomment-346549047 ] same as (3) PR: #962 [FIXED]
- [x] (5) https://github.com/owncloud/ios/issues/956 -> not a regression, now visible in server setting due to server bug fixed 
[FIXED] PR: https://github.com/owncloud/ios/pull/962
- [X] (6) [Bug] Fields lost in share link  https://github.com/owncloud/ios/issues/923#issuecomment-344665947 
[FIXED, upgrade db, active user, add accounts, switch accounts] Not a regression, PR: https://github.com/owncloud/ios/pull/960 
- [X] (7) [Bug] Session expired with av. offline files https://github.com/owncloud/ios/issues/923#issuecomment-344854841 ~~check https://github.com/owncloud/ios/pull/850~~  [FIXED] PR: https://github.com/owncloud/ios/pull/974
- [X] (8) [Bug] Error when changes share privileges https://github.com/owncloud/ios/issues/923#issuecomment-344863474 [FIXED] Fixed in library https://github.com/owncloud/ios-library/pull/168/commits/e632bb0cf486659727b7d133c7fb2de1b16586a2
- [X] (9)Remove predict keyboard from login view fields  [FIXED] 
- [x] (10) OAuth2 session does not expire the first time token expires https://github.com/owncloud/ios/issues/923#issuecomment-345187847 [BLOCKED] server issue, https://github.com/owncloud/oauth2/issues/103  ~~workaround https://github.com/owncloud/ios/pull/973~~
- [x] (11) (imprvmnt) Wording in login view https://github.com/owncloud/ios/issues/923#issuecomment-346008738
[FIXED] https://github.com/owncloud/ios/pull/961
- [X] (12) https://github.com/owncloud/ios/issues/923#issuecomment-347477360  PR: https://github.com/owncloud/ios/pull/970 [FIXED]
- [X] (13)  Improve network error message after check url if path not found [FIXED] PR: https://github.com/owncloud/ios/pull/968
- [X] (14) Issue open with iOS11 [WON'T FIX here, will be handle next release with iOS11 support] more details, https://github.com/owncloud/ios/issues/923#issuecomment-352373089, https://github.com/owncloud/ios/issues/980

**Comment by nasli** [comment]
BUG
### Steps to reproduce
1. create public link on 8.2.x server
2. use "copy to clipboard" feature

### Expected behaviour
iOS app shouldn't crash, even with older owncloud version

### Actual behaviour
iOS app 3.5.6 crashes always

### Server configuration

**ownCloud version:** (see ownCloud admin page)
8.2.x

### Client
**iOS version:**
iOS 9.3.5

**ownCloud app version:**
3.6.2

**Device model:**
iPad 2

**Comment by jesmrec** [comment]
### BUG (2) (low)

### Steps to reproduce
1. Create an account in OAuth2 server
2. Go to settings view and select "Create new account"
3. Input the same credentials of the account in 1.

### Current behaviour
Error message is displayed correctly and webview shows "Authorization" button, skipping credentials.

### Expected behaviour
Error message is displayed correctly and webview shows fields to input credentials

iPhone10 v10. Server10.0.4

**Comment by jesmrec** [comment]
### BUG (5) (medium)

### Steps to reproduce
1. Create an account in OAuth2 server
2. Go to settings view and select "Edit credentials"

### Current behaviour
Webview shows "Authorization" button, skipping credentials.

### Expected behaviour
Webview shows fields to input credentials before authorizating

iPhone10 v10. Server10.0.4

**Comment by jesmrec** [comment]
### BUG (5) (medium)

### Steps to reproduce
1. install the app from scratch with a server 10, for example 10.0.3
2. Enter credentials (no matter auth method) -> Login View
3. Try to share by link  a file or folder-> all info is correct displayed (link name, password, expiration...)
4. Kill the app and open it again
5. Try to share by link a file or folder

### Current behaviour
Field "Link Name" does not appear. Field "Show file listing" (for folders) does not appear

### Expected behaviour
All fields appear, so the server is version 10 or newer, where these fields were introduced (in the case of show file listing, was introduced in 10.0.1)

iPad Air v10.3. Server10.0.3 (SAML/OAuth2/basic)

It was checked the responsed JSON of the capabilities request when the app is opened for the steps 2. and 5. Both were the same:

```
{
    "ocs": {
        "data": {
            "capabilities": {
                "checksums": {
                    "preferredUploadType": "SHA1", 
                    "supportedTypes": [
                        "SHA1"
                    ]
                }, 
                "core": {
                    "pollinterval": 60, 
                    "status": {
                        "edition": "Enterprise", 
                        "installed": true, 
                        "maintenance": false, 
                        "needsDbUpgrade": false, 
                        "productname": "ownCloud", 
                        "version": "10.0.3.3", 
                        "versionstring": "10.0.3"
                    }, 
                    "webdav-root": "remote.php/webdav"
                }, 
                "dav": {
                    "chunking": "1.0"
                }, 
                "files": {
                    "bigfilechunking": true, 
                    "blacklisted_files": [
                        ".htaccess"
                    ], 
                    "privateLinks": true, 
                    "undelete": true, 
                    "versioning": true
                }, 
                "files_sharing": {
                    "api_enabled": true, 
                   "default_permissions": 31, 
                    "federation": {
                        "incoming": true, 
                        "outgoing": true
                    }, 
                    "group_sharing": true, 
                    "public": {
                        "enabled": true, 
                        "expire_date": {
                            "enabled": false
                        }, 
                        "multiple": true, 
                        "password": {
                            "enforced": false
                        }, 
                        "send_mail": false, 
                        "social_share": true, 
                        "supports_upload_only": true, 
                        "upload": true
                    }, 
                    "resharing": true, 
                    "share_with_group_members_only": true, 
                    "share_with_membership_groups_only": true, 
                    "user": {
                        "send_mail": false
                    }, 
                    "user_enumeration": {
                        "enabled": true, 
                        "group_members_only": false
                    }
                }, 
                "notifications": {
                    "ocs-endpoints": [
                        "list", 
                        "get", 
                        "delete"
                    ]
                }
            }, 
            "version": {
                "edition": "Enterprise", 
                "major": 10, 
                "micro": 3, 
                "minor": 0, 
                "string": "10.0.3"
            }
        }, 
        "meta": {
            "itemsperpage": "", 
            "message": "OK", 
            "status": "ok", 
            "statuscode": 100, 
            "totalitems": ""
        }
    }
}
```

**Comment by jesmrec** [comment]
### BUG (6) (medium) 

### Steps to reproduce
1. Login with SAML account
2. Set a file (not a folder) as available offline.
3. Wait until session expires (or force it)
4. Input credentials

### Current behaviour
Webview does not disappear and seems to be stucked. By killing it and open the app again, the session has started.

### Expected behaviour
Webview disappears after inputing correct credentials.

iPadMini  v10.1.1. Server10.0.4

**Comment by jesmrec** [comment]
### BUG (8) 

### Steps to reproduce
1. Share with another user (no matter if file or folder, no matter auth type)
2. Open privileges view of this share and try to modify any of the privileges

### Current behaviour
`Wrong or no update parameter given`

### Expected behaviour
Privileges changed

iPadMini  v10.1.1. Server10.0.4
iPhone v10.0.1

**Comment by nasli** [comment]
@jesmrec please review (5) https://github.com/owncloud/ios/issues/956

**Comment by jesmrec** [comment]
### BUG (10) 

### Steps to reproduce
1. Install from scratch
2. Open a new OAuth2 session
3. Make the token expire
4. Perform more actions

### Current behaviour
Token is not renewed. By killing the app and open it again, the token expires and from this moment, token expires correctly

### Expected behaviour
Correct expirations from the beginning.

iPadMini  v10.1.1. Server10.0.4
iPhone v10.0.1

**Comment by jesmrec** [comment]
### IMPRVMT (10) 

Some wording issues in login view:

`Secure Connection Established` -> `Secure Connection`  
`Connection Established` -> `Non-secure connection`

to avoid a discrepance between the word `Connection` and the button label `Connect`

**Comment by nasli** [comment]
@jesmrec New fix for handling cookies https://github.com/owncloud/ios/pull/962,

**Comment by jesmrec** [comment]
@nasli about (4): the first time after installing that you try to edit credentials, credentials are not asked. After that, credentials are always asked

**Comment by nasli** [comment]
Bug (8)https://github.com/owncloud/ios/issues/923#issuecomment-344863474  related sharees, ready to test @jesmrec

**Comment by nasli** [comment]
Bug (10) Related OAuth session expired, forcing directly from the database makes the cookies does not expire, and with the fix from cookies now when you open the app, we keep using same cookies, so session never expire. 
Try with a lower timing expiration and remove session from server settings UI.

Could be an issue in OAuth, if you remove from OAuth settings the sessions, the cookies keep alive..

**Comment by jesmrec** [comment]
### BUG (12) 

### Steps to reproduce
1. Install from scratch
2. Open a new SAML session
3. Wait until expires (or force it)
4. Input credentials again and perform any action

### Current behaviour
Login view is raised again

### Expected behaviour
Session starts and usen can perform as many actions as he wants

iPadMini  iOS10.1.1. Server10.0.3
iPhone iOS9 Server10.0.3

**Comment by nasli** [comment]
Bug (12) seems to be the same as (7), looking it

**Comment by nasli** [comment]
Bug (12) fixed within https://github.com/owncloud/ios/pull/970, (7) will be handle in different issue

**Comment by nasli** [comment]
Bug (7) reday to test @jesmrec PR: https://github.com/owncloud/ios/pull/974

**Comment by nasli** [comment]
Please @jesmrec take a look at this pr https://github.com/owncloud/ios/pull/976 to check issue with duplicate accounts, thanks!

**Comment by ChrisEdS** [comment]
[iOS11] No sharing windows present
[https://github.com/owncloud/ios/issues/980](url)

##Steps to reproduce
1. Open ownCloud-App in iOS11
2. Go to a file (PDF as example)
3. Try to open the file in another app

## Expected behaviour
The "sharing-window" appears

## Actual behaviour
Nothing appears

Same when you swipe right on a file and try to "open with"

Client
#iOS version:
11.1.2

**Comment by jesmrec** [comment]
About BUG (13), the problem only happens when the app is installed from scratch and can be avoided when the app is opened after killing or after background (Could you check @ChrisEdS ?) as workaround.

**Comment by ChrisEdS** [comment]
You're right, Jesus. After a quit and restart it works. Exactly once. Either with swipe or over the button. Unfortunately, this workaround does not work for the my wrapped MDM version.

**Comment by ChrisEdS** [comment]
It sounds crazy but I think the menu is there but invisible. After the "Open With" order, the app does not respond exactly to the area where the menu would normally be. If I press on an area that would not be covered by the menu (the menu will disappear normally), everything will react again.

In summary, I believe that the menu is already there - but "invisible". Maybe that helps with troubleshooting.

**Comment by nasli** [comment]
Bug (14) could be related with a changes in permissions in iOS 11, the app bundle url we share, maybe we need to use a temporal folder to share it.

**Comment by jesmrec** [comment]
At this point all the bugs are fixed.
