### ISSUE TITLE
Release new version 3.7.1

### ISSUE THREAD

**Issue by nasli** [owncloud/ios#986]
#Release a new version
## TASKS:
- [ ] [GIT] Create branch release_3.7.1 (freeze the code)
- [ ] [GIT] Create branch library release_2.2.1_library (freeze the code)
- [ ] [DIS] Update changelog ios app
- [ ] [DEV] Update version number
- [ ] [DEV] Update readme number version app and library, xcode version
- [ ] [DEV] Update third party file
- [ ] [DEV] Get latest translations from master
- [ ] [QA] Design Test plan @jesmrec
- [ ] [QA] Regression Test  @jesmrec 
- [ ] [DIS] Update screenshots. iPhone 5.8"
- [ ] [DIS] Create itunes new version
- [ ] [DIS] Upload new ipa to appstore
- [ ] [GIT] Merge branch release
- [ ] [GIT] Merge branch library release
- [ ] [GIT] Create tag and sign it
- [ ] Ping to publish in social media

PR: 
PR library:

**Comment by jesmrec** [comment]
### Bug (1)

1. Login in a SAML account
2. Wait / force session expiration
3. Enter credentials of a different user

Current: Login with different user
Expected: Error message indication that the user is not the correct one, and no login

Tested with iPhone 6SPlus, iPadAir.

**Comment by jesmrec** [comment]
### Bug (2)

1. Login in a basic auth account
2. In web UI, change the password of the user
3. In device, pull down -> redirected to login view

Current: Message about session expiration
Expected: Message about credentials error

Tested with iPhone 6SPlus, iPadAir.

**Comment by jesmrec** [comment]
### Bug (3)

1. Install previous version, for example 3.6.2
2. Enable instant uploads for pics, videos, and background option
3. Upgrade to the current version

Current: Some stuff (videos) is queued in uploads view, and uploaded and instant uploads
Expected: Anything queued

Tested with iPhone 6SPlus v11.2.5

**Comment by jesmrec** [comment]
Bug (1) not reproducible anymore in the release branch. Set as not reproducible. Sorry for the noise

**Comment by jesmrec** [comment]
### Bug (4)

Preview MSOffice format files (doc(x), xls(x), ppt(x)

Current: Blank
Expected: File previewed

Tested with iPhone 6SPlus v11.2.5, iPadAir v11

**Comment by jesmrec** [comment]
### Bug (5)

Steps:

1. User1 shares with User2 a folder without delete permission
2. User2 tries to delete

Current: Blank error message
Expected: Correct Error Message

Tested with iPhone 6SPlus v11.2.5, iPadAir v11

**Comment by nasli** [comment]
Ok, all bugs fixed except number 3, I cannot reproduce it yet

**Comment by jesmrec** [comment]
At this point, oauth2 depending this issue: https://github.com/owncloud/oauth2/issues/117 in renewal cases. For not-renewal, working as expected.

**Comment by jesmrec** [comment]
OAuth2 bug fixed: https://github.com/owncloud/oauth2/pull/118

**Comment by nasli** [comment]
@jesmrec with your steps I can reproduce, should be fixed, please review it

**Comment by jesmrec** [comment]
all stuff fixed. Approved
